### ISSUE TITLE
Using scheduled cube refresh endpoint not working with Athena

### ISSUE THREAD

**Issue by tobilg** [cube-js/cube.js#1000]
**Describe the bug**
When trying to hit the /run-scheduled-refresh endpoint as described in https://cube.dev/docs/rest-api#api-reference-v-1-run-scheduled-refresh, an error is returned:

```text
{"error":"TypeError: Cannot read property '1' of undefined"}
```

There's also a detailed stack trace in the logs:

```text
{
    "message": "Refresh Scheduler Error",
    "error": "TypeError: Cannot read property '1' of undefined\n    at BaseTimeDimension.dateTo (/var/task/node_modules/@cubejs-backend/schema-compiler/adapter/BaseTimeDimension.js:130:64)\n    at BaseTimeDimension.dateToParam (/var/task/node_modules/@cubejs-backend/schema-compiler/adapter/BaseTimeDimension.js:137:46)\n    at PrestodbQuery.incrementalRefreshKey (/var/task/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1819:99)\n    at cacheValue.inputProps.collectOriginalSqlPreAggregations (/var/task/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1851:33)\n    at PrestodbQuery.evaluateSymbolSqlWithContext (/var/task/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1355:22)\n    at /var/task/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:141:25\n    at QueryCache.cache (/var/task/node_modules/@cubejs-backend/schema-compiler/adapter/QueryCache.js:17:28)\n    at PrestodbQuery.cacheValue (/var/task/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:136:66)\n    at PrestodbQuery.preAggregationInvalidateKeyQueries (/var/task/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1829:17)\n    at PreAggregations.preAggregationDescriptionFor (/var/task/node_modules/@cubejs-backend/schema-compiler/adapter/PreAggregations.js:102:42)",
    "authInfo": {
        "u": {
            "customerId": "ac2011e1-a2f3-4002-9cb0-66c0fb8d839f",
            "userName": "ac2011e1-a2f3-4002-9cb0-66c0fb8d839f",
            "isAdmin": false
        }
    },
    "requestId": "886726f2-f901-4c02-9d4f-dc0022d50a77"
}
```

**To Reproduce**
E.g. `curl -G -vv https://YOURENDPOINT/cube-api/v1/run-scheduled-refresh`

**Expected behavior**
Cube refresh via API works as planned

**Version:**
Latest, with local patch for https://github.com/cube-js/cube.js/commit/2d3018d7045b1c5ee3aeeee8d469c4d6bc343018

**Additional context**
Cube.js is deployed Serverless-ly on AWS, running an Elasticache, Aurora Serverless and Athena

**Comment by paveltiunov** [comment]
@tobilg Hey Tobi! Could you please share your schema?

**Comment by tobilg** [comment]
Hi @paveltiunov, 

this is the schema (raw SQL is omitted):

```javascript
cube(`PV`, {
  sql: `...OMITTED...`,

  measures: {
    pageViews: {
      sql: `page_views_count`,
      type: `sum`,
      title: `Number of Page Views`
    },
    uniquePageViews: {
      sql: `unique_page_views_count`,
      type: `sum`,
      title: `Number of Unique Page Views`
    },
    uniqueVisits: {
      sql: `unique_visits_count`,
      type: `sum`,
      title: `Number of Unique Visits`
    },
    bounces: {
      sql: `bounces_count`,
      type: `sum`,
      title: `Number of Bounces`
    },
    avgDeviceMemory: {
      sql: `avg_device_memory`,
      type: `avg`,
      title: `Average Device Memory`
    },
    avgDeviceCores: {
      sql: `avg_device_cores`,
      type: `avg`,
      title: `Average Device Cores`
    }
  },
  
  dimensions: {
    edgeCity: {
      sql: `edge_city`,
      type: `string`,
      title: `City`
    },

    edgeCountry: {
      sql: `edge_country`,
      type: `string`,
      title: `Country`
    },

    edgeLatitude: {
      sql: `edge_latitude`,
      type: `number`,
      title: `Latitude`
    },

    edgeLongitude: {
      sql: `edge_longitude`,
      type: `number`,
      title: `Longitude`
    },
    
    path: {
      sql: `path`,
      type: `string`,
      title: `Path`
    },
    
    referrerDomainName: {
      sql: `referrer_domain_name`,
      type: `string`,
      title: `Referrer Domain Name`
    },

    browserName: {
      sql: `browser_name`,
      type: `string`,
      title: `Browser Name`
    },

    browserPlatform: {
      sql: `browser_platform`,
      type: `string`,
      title: `Browser Platform`
    },

    browserOs: {
      sql: `browser_os`,
      type: `string`,
      title: `Browser OS`
    },
    
    browserLanguage: {
      sql: `browser_language`,
      type: `string`,
      title: `Browser Language`
    },

    utmSource: {
      sql: `utm_source`,
      type: `string`,
      title: `UTM Source`
    },
    
    utmCampaign: {
      sql: `utm_campaign`,
      type: `string`,
      title: `UTM Campaign`
    },
    
    utmMedium: {
      sql: `utm_medium`,
      type: `string`,
      title: `UTM Medium`
    },
    
    utmContent: {
      sql: `utm_content`,
      type: `string`,
      title: `UTM Content`
    },
    
    utmTerm: {
      sql: `utm_term`,
      type: `string`,
      title: `UTM Term`
    },

    domainName: {
      sql: `domain_name`,
      type: `string`,
      title: `Domain Name`
    },

    customerId: {
      sql: `customer_id`,
      type: `string`,
      title: `Customer ID`
    },

    eventDate: {
      sql: `event_date`,
      type: `time`,
      title: `Date`
    },
  },

  refreshKey: {
    sql: `SELECT MAX(event_timestamp) FROM prod.page_views`
  },

  preAggregations: {
    main: {
      type: `rollup`,
      measureReferences: [
        PV.pageViews,
        PV.uniquePageViews,
        PV.uniqueVisits,
        PV.bounces,
        PV.avgDeviceMemory,
        PV.avgDeviceCores
      ],
      dimensionReferences: [
        PV.edgeCity, 
        PV.edgeCountry,
        PV.edgeLatitude,
        PV.edgeLongitude,
        PV.path,
        PV.referrerDomainName,
        PV.browserName,
        PV.browserPlatform,
        PV.browserOs,
        PV.browserLanguage,
        PV.domainName,
        PV.customerId,
        PV.utmSource,
        PV.utmCampaign,
        PV.utmMedium,
        PV.utmContent,
        PV.utmTerm
      ],
      timeDimensionReference: PV.eventDate,
      granularity: `day`,
      partitionGranularity: `day`,
      refreshKey: {
        every: `1 hour`,
        incremental: true,
        updateWindow: `1 day`
      },
      external: true,
      scheduledRefresh: true
    }
  }
});
```

**Comment by tobilg** [comment]
I just checked you change, that fixes the error message for me @paveltiunov... Thanks a lot!
