### ISSUE TITLE
Potential issue with queryTransformer example

### ISSUE THREAD

**Issue by mwhipple** [cube-js/cube.js#1007]
**Problem**

I'm picking through an issue with a queryTransformer providing authorization throwing an error.
The queryTransformer is of a similar pattern to the example here: https://cube.dev/docs/@cubejs-backend-server-core#options-reference-query-transformer

The error is ultimately thrown here: https://github.com/cube-js/cube.js/blob/cecdb36c6999f2a79e17a4b0ef5c2d295300277d/packages/cubejs-schema-compiler/compiler/CubeEvaluator.js#L112
seemingly due to no existing dimension from:
https://github.com/cube-js/cube.js/blob/master/packages/cubejs-schema-compiler/adapter/BaseQuery.js#L83

It looks like that would normally be avoided through the query normalization here:
https://github.com/cube-js/cube.js/blob/master/packages/cubejs-api-gateway/index.js#L235

but that normalization is called prior to the transformer and therefore it seems to be breaking due to dimension missing but being expected.

Does that sound accurate or am I missing something?

**Comment by paveltiunov** [comment]
@mwhipple Hey Matt! Could you please share your `queryTransformer` implementation and Cube.js schema?

**Comment by mwhipple** [comment]
Sure here's the starting point:
#### queryTransformer
```javascript
const queryTransformer = (query, { authInfo }) => {
  const organizationId = authInfo && authInfo.u && authInfo.u.organizationId
  if (organizationId) {
    query.filters.push({
      member: 'organizationId',
      operator: 'equals',
      values: [organizationId]
    })
  }
  return query
};
```

#### schema
```javascript
cube(`FctDeskBookedByDate`, {
  sql: `SELECT * FROM dw.fct_desk_booked_by_date`,

  joins: {
    DimDate: {
      relationship: `belongsTo`,
      sql: `${FctDeskBookedByDate}.date_dimension_fk = ${DimDate}.date_dim_id`
    },
    DimDesk: {
      relationship: `belongsTo`,
      sql: `${FctDeskBookedByDate}.desk_dimension_fk = ${DimDesk}.dbt_scd_id`
    },
  },

  measures: {
    desksBookableCount: {
      type: `count`,
      drillMembers: [
        desk_id,
        DimDesk.name,
        DimDesk.podName,
        DimDesk.spaceName,
        DimDesk.levelName,
        DimDesk.locationName,
        DimDesk.campusName,
        DimDesk.organizationName
      ]
    },
    desksBookedCount: {
      type: `count`,
      filters: [
        { sql: `${FctDeskBookedByDate}.booked > 0` }
      ],
      drillMembers: [
        desk_id,
        DimDesk.name,
        DimDesk.podName,
        DimDesk.spaceName,
        DimDesk.levelName,
        DimDesk.locationName,
        DimDesk.campusName,
        DimDesk.organizationName
      ]
    },
    desksNotBookedCount: {
      type: `count`,
      filters: [
        { sql: `${FctDeskBookedByDate}.booked < 1` }
      ],
      drillMembers: [
        desk_id,
        DimDesk.name,
        DimDesk.podName,
        DimDesk.spaceName,
        DimDesk.levelName,
        DimDesk.locationName,
        DimDesk.campusName,
        DimDesk.organizationName
      ]
    }
  },

  dimensions: {
    id: {
      sql: `id`,
      type: `string`,
      primaryKey: true
    },
    desk_id: {
      sql: `desk_id`,
      type: 'number'
    },
    isBooked: {
      sql: `booked`,
      type: 'number'
    },
    organizationId: {
      sql: `${DimDesk}.organization_id`,
      type: 'number'
    }
  }
});
//-----
cube(`DimDate`, {
  sql: `SELECT * FROM dw.dim_date`,

  joins: {
    FctDeskBookedByDate: {
      relationship: `hasMany`,
      sql: `${FctDeskBookedByDate}.date_dimension_fk = ${DimDate}.date_dim_id`
    },
  },

  measures: {
  },

  dimensions: {
    date_dim_id: {
      sql: `date_dim_id`,
      type: 'number',
      primaryKey: true
    },
    monthName: {
      sql: `month_name`,
      type: `string`
    },

    monthNameAbbreviated: {
      sql: `month_name_abbreviated`,
      type: `string`
    },

    daySuffix: {
      sql: `day_suffix`,
      type: `string`
    },

    dayName: {
      sql: `day_name`,
      type: `string`
    },

    weekOfYearIso: {
      sql: `week_of_year_iso`,
      type: `string`
    },

    quarterName: {
      sql: `quarter_name`,
      type: `string`
    },

    weekendIndr: {
      sql: `weekend_indr`,
      type: `string`
    },

    dateActual: {
      sql: `date_actual`,
      type: `time`
    },

    firstDayOfWeek: {
      sql: `first_day_of_week`,
      type: `time`
    },

    lastDayOfWeek: {
      sql: `last_day_of_week`,
      type: `time`
    },

    firstDayOfMonth: {
      sql: `first_day_of_month`,
      type: `time`
    },

    lastDayOfMonth: {
      sql: `last_day_of_month`,
      type: `time`
    },

    firstDayOfQuarter: {
      sql: `first_day_of_quarter`,
      type: `time`
    },

    lastDayOfQuarter: {
      sql: `last_day_of_quarter`,
      type: `time`
    },

    firstDayOfYear: {
      sql: `first_day_of_year`,
      type: `time`
    },

    lastDayOfYear: {
      sql: `last_day_of_year`,
      type: `time`
    }
  }
});
//-----
cube(`DimDesk`, {
  sql: `SELECT * FROM dw.dim_desk`,

  joins: {
    FctDeskBookedByDate: {
      relationship: 'hasMany',
      sql: `${FctDeskBookedByDate}.desk_dimension_fk = ${DimDesk}.dbt_scd_id`
    }
  },

  measures: {
  },

  dimensions: {
    id: {
      sql: `id`,
      type: `number`
    },

    name: {
      sql: `name`,
      type: `string`
    },

    podName: {
      sql: `pod_name`,
      type: `string`
    },

    bookingPolicy: {
      sql: `booking_policy`,
      type: `string`
    },

    spaceName: {
      sql: `space_name`,
      type: `string`
    },

    levelName: {
      sql: `level_name`,
      type: `string`
    },

    locationName: {
      sql: `location_name`,
      type: `string`
    },

    campusName: {
      sql: `campus_name`,
      type: `string`
    },

    organizationName: {
      sql: `organization_name`,
      type: `string`
    },

    organizationId: {
      sql: `organization_id`,
      type: `number`
    },

    dbtScdId: {
      sql: `dbt_scd_id`,
      type: `string`,
      primaryKey: true
    },

    createdAt: {
      sql: `created_at`,
      type: `time`
    },

    dbtUpdatedAt: {
      sql: `dbt_updated_at`,
      type: `time`
    },

    updatedAt: {
      sql: `updated_at`,
      type: `time`
    },

    disabledAt: {
      sql: `disabled_at`,
      type: `time`
    },

    spaceDisabledAt: {
      sql: `space_disabled_at`,
      type: `time`
    },

    dbtValidFrom: {
      sql: `dbt_valid_from`,
      type: `time`
    },

    dbtValidTo: {
      sql: `dbt_valid_to`,
      type: `time`
    }
  }
});
```

Upon attempted use that produces (sorry for the formatting):
```
 Internal Server Error: {"query":{"measures":["FctDeskBookedByDate.desksBookedCount"]},"error":"TypeError: Cannot read property 'split' of undefined\n    at CubeEvaluator.isInstanceOfType (/app/node_modules/@cubejs-backend/schema-compiler/compiler/CubeEvaluator.js:112:59)\n    at CubeEvaluator.isMeasure (/app/node_modules/@cubejs-backend/schema-compiler/compiler/CubeEvaluator.js:68:17)\n    at /app/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:84:30\n    at Array.map (<anonymous>)\n    at PostgresQuery.initFromOptions (/app/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:83:50)\n    at new BaseQuery (/app/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:45:10)\n    at new PostgresQuery (/app/node_modules/@cubejs-backend/schema-compiler/adapter/PostgresQuery.js:20:1)\n    at Object.exports.query (/app/node_modules/@cubejs-backend/schema-compiler/adapter/QueryBuilder.js:41:10)\n    at CompilerApi.createQuery (/app/node_modules/@cubejs-backend/server-core/core/CompilerApi.js:102:25)\n    at CompilerApi.createQueryByDataSource (/app/node_modules/@cubejs-backend/server-core/core/CompilerApi.js:98:17)","duration":5,"authInfo":{"u":{"userId":1,"organizationId":18}},"requestId":"76126508-cc48-470e-aa31-fcb401e2ccae"}
```

**Comment by mwhipple** [comment]
FWIW I don't necessarily expect the current configuration to be valid (which is what I'm currently looking at) but the error produced by the above is at best abstruse. Replacing `member` with `dimension` in the queryTransformer produces far more cogent messages around potential model issues (presumably the first being caused by the use of a relative path in a place where it can't be expanded).

**Comment by mwhipple** [comment]
A working approach from a schema perspective seems to be to add a stable outrigger dimension so that the path in the queryResolver can be qualified as part of that dimension and then the row level filtering can be satisfied through the transitive joins. This is basically a different thread than the original issue around `member` vs. `dimension` but I'd certainly love to hear if there's any suggested simpler alternatives using some kind of relative field to support multi-tenancy with row-level security where the required predicate field could be in different dimensions.

**Comment by jcw-** [comment]
@mwhipple Have you tried specifying the cube name? You should be able to derive it by inspecting the rest of the `query` object, and then use this format:
```
dimension: `${cube}. organizationId`
```

**Comment by mwhipple** [comment]
Specifying the cube name and arranging the model to guarantee a consistent absolute path for the needs works without a problem.

My specific needs are addressed but question remains around documentation bugs or gaps in the exampled linked above where `member` is used rather than `dimension`. `member` didn't work (and doesn't look like it should when skimming the code) and that may have other implications if `member` normally carries behavior which provided through query normalization which is applied prior to the queryTransformer (for example does `member` normally support relative paths?). Having a library blow up with an internal null pointer doesn't seem desirable in any case but particularly so when it's thrown from code based on documented examples.

**Comment by paveltiunov** [comment]
@mwhipple Yep. It seems like a bug. For backward compatibility it probably should normalize a query the way it contains bot `dimension` and `member`.
