### ISSUE TITLE
Cubejs backend is not returning data queried by React frontend

### ISSUE THREAD

**Issue by agnuku** [cube-js/cube.js#1471]
**Describe the bug**
Cubejs backend deployed on Heroku container is not returning data queried by React frontend deployed on Vercel. Server logs indicate an error: `TypeError: Cannot create proxy with a non-object as target or handler\n    at PostgresQuery.contextSymbolsProxy`. See full error output below.

**To Reproduce**

**1. Schema**
```javascript
cube(`Activity`, {
  sql: `SELECT * FROM public.activity`,

  joins: {

  },

  measures: {
    count: {
      type: `count`,
      drillMembers: [id, sourceId, createdat, updatedat]
    }
  },

  dimensions: {
    link: {
      sql: `link`,
      type: `string`
    },

    feature1: {
      sql: `feature_1`,
      type: `string`,
      title: `Feature 1`
    },

    feature2: {
      sql: `feature_2`,
      type: `string`,
      title: `Feature 2`
    },

    activity: {
      sql: `activity`,
      type: `string`
    },

    source: {
      sql: `source`,
      type: `string`
    },

    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true
    },

    sourceId: {
      sql: `source_id`,
      type: `string`
    },

    createdat: {
      sql: `${CUBE}."createdAt"`,
      type: `time`
    },

    updatedat: {
      sql: `${CUBE}."updatedAt"`,
      type: `time`
    },

    ts: {
      sql: `ts`,
      type: `time`
    }
  }
});
```

**2. Query**

```javascript
const cubejsApi = cubejs(CUBEJS_TOKEN, {

  apiUrl: `${API_URL}/cubejs-api/v1`,
});

const Cube = () => {
  return (
    <QueryRenderer
      query={{
        measures: ["Activity.count"],
        dimensions: ["Activity.activity"],
      }}
      cubejsApi={cubejsApi}
      render={({ resultSet }) => {
        if (!resultSet) {
          return "Loading...";
        }

        return (
          <LineChart data={resultSet.rawData()}>
            <XAxis dataKey="Activity.activity" />
            <YAxis />
            <Line type="monotone" dataKey="Activity.count" stroke="#8884d8" />
          </LineChart>
        );
      }}
    />
  );
};

export default Cube;
```

**3. Response**

```
{
    "message":"Internal Server Error",
    "query": {
        "measures": ["Activity.count"],"dimensions":["Activity.activity"]},
        "error":"TypeError: Cannot create proxy with a non-object as target or handler\n
            at PostgresQuery.contextSymbolsProxy (/cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:2080:12)\n
            at /cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:2072:27\n
            at XWrap.f (/cube/node_modules/ramda/src/map.js:78:20)\n
            at XWrap.@@transducer/step (/cube/node_modules/ramda/src/internal/_xwrap.js:17:17)\n
            at _arrayReduce (/cube/node_modules/ramda/src/internal/_reduce.js:18:34)\n
            at _reduce (/cube/node_modules/ramda/src/internal/_reduce.js:60:12)\n
            at map (/cube/node_modules/ramda/src/map.js:77:14)\n
            at /cube/node_modules/ramda/src/internal/_dispatchable.js:50:15\n
            at Object.f2 [as map] (/cube/node_modules/ramda/src/internal/_curry2.js:34:14)\n
            at PostgresQuery.parametrizedContextSymbols (/cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:2071:12)\n
            at PostgresQuery.evaluateSql (/cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1386:28)\n
            at PostgresQuery.autoPrefixAndEvaluateSql (/cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1351:55)\n
            at PostgresQuery.evaluateSymbolSql (/cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1342:21)\n
            at PostgresQuery.primaryKeySql (/cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1585:17)\n
            at PostgresQuery.evaluateSymbolSql (/cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1309:62)\n
            at PostgresQuery.traverseSymbol (/cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1078:35)\n
            at /cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1109:31\n
            at PostgresQuery.evaluateSymbolSqlWithContext (/cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1446:22)\n
            at PostgresQuery.collectCubeNamesFor (/cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1402:10)\n
            at /cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1109:17\n
            at CompilerCache.cache (/cube/node_modules/@cubejs-backend/schema-compiler/adapter/QueryCache.js:22:28)\n
            at /cube/node_modules/@cubejs-backend/schema-compiler/adapter/BaseQuery.js:1105:39",
        "duration":2,
        "authInfo":{"u":"xxxxxxxxxxxxx","iat":xxxxxxxx,"exp":xxxxxxxx},
        "requestId":"xxxxxxxxxxxxxxx-span-1"
    }
}
```

**Expected behavior**
Expected cubejs server to return requested data to the React frontend.  

**Screenshots**
Not needed

**Version:**
0.23.12

**Additional context**
None

**Comment by ovr** [comment]
Hello @agnuku,

I am not able to reproduce this issue locally (I am using the latest Cube.js release), maybe you have an issue with this https://github.com/cube-js/cube.js/blob/ee38689228eac3d6757763d72d6da063791f60da/docs/content/Authentication-%26-Authorization.md#security-context

Do you pass an Authorization token?

Thanks

**Comment by agnuku** [comment]
Hello @ovr ,
I do pass an authorization token. I went ahead and scrapped the project with the above issue today and started a fresh cubejs project. Everything works locally, but getting an invalid token on queries when deployed to heroku. 
Let's go ahead and close this issue. I'll reach out on slack if still running into issues. 
Thanks.
