### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by benswinburne** [cube-js/cube.js#1597]
**Describe the bug**
When I run my Cube and it begins to run the pre-aggregations I repeatedly get the error message

> TypeError: Cannot convert undefined or null to object

I noticed that one of the queries it is trying to run is to get data for the 15th (+1 day) at the time of writing which may be a bug, may be how my Cube is set up. I don't see how my configuration would account for +1 day?

It is querying athena and rolling up into mysql.

```
cube(`Events`, {
  sql: `SELECT * FROM events.events`,

  refreshKey: {
    every: `1 hour`,
  },

  measures: {...},

  dimensions: {...},

  preAggregations: {
    perfDay: {
      type: `rollup`,
      indexes: {
        creativeId: {
          columns: [creativeId],
        },
      },
      measureReferences: [
        impressions,
        engagements,
        interactions,
        conversations,
        messages,
        clicks,
        videoPlays,
        dwellCount,
        totalDwellTimeInSeconds,
      ],
      dimensionReferences: [creativeId, touchDevice],
      timeDimensionReference: dt,
      granularity: `day`,
      partitionGranularity: `day`,
      external: true,
      refreshKey: {
        every: `13 * * * *`, // Don't do it on the hour because of contention for athena resources
        incremental: true,
        updateWindow: `1 day`,
      },
      scheduledRefresh: true,
      refreshRangeStart: {
        sql: `SELECT to_iso8601(NOW() - interval '30' day)`,
      },
      refreshRangeEnd: {
        sql: `SELECT to_iso8601(NOW())`,
      },
    },
  }
}
```

It is my understanding that the above would get 30 days worth of data, segmented into 30 tables covering one day each.

It seems that this line expects there to always be a row returned 

https://github.com/cube-js/cube.js/blob/master/packages/cubejs-query-orchestrator/src/driver/BaseDriver.js#L127

and in the case of this problem there is nothing for Object.keys to run against.

**Expected behavior**

1. to handle queries which return no rows without errors
2. to not create refresh keys in the future (if it's not something odd i'm doing)

**Version:**
```
  "devDependencies": {
    "@cubejs-backend/athena-driver": "^0.24.6",
    "@cubejs-backend/mysql-driver": "^0.24.7",
    "@cubejs-backend/server": "^0.24.6"
  }
```

**Additional context**

```
cube_1   | Executing Load Pre Aggregation SQL: scheduler-fc69195f-de74-43d7-954e-6bdce2914b08
cube_1   | --
cube_1   |   SELECT
cube_1   |       "events".creative_id "events__creative_id", "events".touch_device "events__touch_device", date_trunc('day', CAST(date_add('minute', timezone_minute(date_parse(dt, '%Y-%m-%d') AT TIME ZONE 'UTC'), date_add('hour', timezone_hour(date_parse(dt, '%Y-%m-%d') A
T TIME ZONE 'UTC'), date_parse(dt, '%Y-%m-%d') AT TIME ZONE 'UTC')) AS TIMESTAMP)) "events__dt_day", count(CASE WHEN ("events".event = 'click') THEN "events".event_id END) "events__clicks", count(CASE WHEN ("events".event = 'conversation') THEN "events".event_id END) "eve
nts__conversations", count(CASE WHEN ("events".clicked = true and "events".event = 'dwell') THEN "events".event_id END) "events__dwell_count", count(CASE WHEN ("events".event = 'engagement') THEN "events".event_id END) "even
ts__engagements", count(CASE WHEN ("events".event = 'impression') THEN "events".event_id END) "events__impressions", count(CASE WHEN ("events".event = 'interaction') THEN "events".event_id END) "events__interactions", count(CASE WHEN ("events".event = 'message') THEN "eve
nts".event_id END) "events__messages", sum(CASE WHEN ("events".clicked = true and "events".event = 'dwell') THEN "events".ms/1000 END) "events__total_dwell_time_in_seconds", count(CASE WHEN ("events".event = 'video_play') TH
EN "events".event_id END) "events__video_plays"
cube_1   |     FROM
cube_1   |       events.events AS "events"
cube_1   |   WHERE (date_parse(dt, '%Y-%m-%d') >= from_iso8601_timestamp('2020-12-15T00:00:00Z') AND date_parse(dt, '%Y-%m-%d') <= from_iso8601_timestamp('2020-12-15T23:59:59Z')) GROUP BY 1, 2, 3
cube_1   | --
cube_1   | Error while querying: scheduler-049bcda8-bf1c-4a9c-8d2c-a60c6d4a814e (3003ms)
cube_1   | {
cube_1   |   "processingId": "27",
cube_1   |   "queueSize": 1,
cube_1   |   "queryKey": [
cube_1   |     [
cube_1   |       "CREATE TABLE stb_pre_aggregations.events_perf_day20201215 AS SELECT\n      \"events\".creative_id \"events__creative_id\", \"events\".touch_device \"events__touch_device\", date_trunc('day', CAST(date_add('minute', timezone_minute(date_parse(dt, '%Y-%m-%d') AT TIME ZONE 'UTC'), date_add('hour', timezone_hour(date_parse(dt, '%Y-%m-%d') AT TIME ZONE 'UTC'), date_parse(dt, '%Y-%m-%d') AT TIME ZONE 'UTC')) AS TIMESTAMP)) \"events__dt_day\", count(CASE WHEN (\"events\".event = 'click') THEN \"events\".event_id END) \"events__clicks\", count(CASE WHEN (\"events\".event = 'conversation') THEN \"events\".event_id END) \"events__conversations\", count(CASE WHEN (\"events\".clicked = true and \"events\".event = 'dwell') THEN \"events\".event_id END) \"events__dwell_count\", count(CASE WHEN (\"events\".event = 'engagement') THEN \"events\".event_id END) \"events__engagements\", count(CASE WHEN (\"events\".event = 'impression') THEN \"events\".event_id END) \"events__impressions\", count(CASE WHEN (\"events\".event = 'interaction') THEN \"events\".event_id END) \"events__interactions\", count(CASE WHEN (\"events\".event = 'message') THEN \"events\".event_id END) \"events__messages\", sum(CASE WHEN (\"events\".clicked = true and \"events\".event = 'dwell') THEN \"events\".ms/1000 END) \"events__total_dwell_time_in_seconds\", count(CASE WHEN (\"events\".event = 'video_play') THEN \"events\".event_id END) \"events__video_plays\"\n    FROM\n      events.events AS \"events\"\n  WHERE (date_parse(dt, '%Y-%m-%d') >= from_iso8601_timestamp(?) AND date_parse(dt, '%Y-%m-%d') <= from_iso8601_timestamp(?)) GROUP BY 1, 2, 3",
cube_1   |       [
cube_1   |         "2020-12-15T00:00:00Z",
cube_1   |         "2020-12-15T23:59:59Z"
cube_1   |       ]
cube_1   |     ],
cube_1   |     [
cube_1   |       [
cube_1   |         {
cube_1   |           "_col0": "18610.0"
cube_1   |         }
cube_1   |       ]
cube_1   |     ]
cube_1   |   ],
cube_1   |   "queuePrefix": "SQL_PRE_AGGREGATIONS_STANDALONE_default",
cube_1   |   "timeInQueue": 35
cube_1   | }
cube_1   | TypeError: Cannot convert undefined or null to object
cube_1   |     at Function.keys (<anonymous>)
cube_1   |     at AthenaDriver.downloadQueryResults (/cube/node_modules/@cubejs-backend/query-orchestrator/src/driver/BaseDriver.js:127:27)
cube_1   |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
cube_1   |     at PreAggregationLoader.refreshImplStreamExternalStrategy (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.js:550:23)
cube_1   |     at Object.query (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.js:200:26)
cube_1   |     at QueryQueue.processQuery (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:249:21)
cube_1   | Error querying db: scheduler-049bcda8-bf1c-4a9c-8d2c-a60c6d4a814e
cube_1   | {}
cube_1   | Error: Cannot convert undefined or null to object
cube_1   |     at QueryQueue.parseResult (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:100:13)
cube_1   |     at QueryQueue.executeInQueue (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:89:19)
cube_1   |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
cube_1   |     at PreAggregationLoader.loadPreAggregationWithKeys (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.js:375:7)
cube_1   |     at PreAggregationLoader.loadPreAggregation (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.js:276:26)
cube_1   |     at OrchestratorApi.executeQuery (/cube/node_modules/@cubejs-backend/server-core/core/OrchestratorApi.js:31:20)
cube_1   |     at /cube/node_modules/@cubejs-backend/server-core/core/RefreshScheduler.js:161:9
cube_1   |     at async Promise.all (index 2)
cube_1   |     at RefreshScheduler.refreshPreAggregations (/cube/node_modules/@cubejs-backend/server-core/core/RefreshScheduler.js:153:5)
cube_1   |     at async Promise.all (index 1)
cube_1   |     at RefreshScheduler.runScheduledRefresh (/cube/node_modules/@cubejs-backend/server-core/core/RefreshScheduler.js:95:7)
cube_1   |     at /cube/node_modules/@cubejs-backend/server-core/core/index.js:275:15
cube_1   |     at async Promise.all (index 0)
cube_1   |     at Timeout._onTimeout (/cube/node_modules/@cubejs-backend/server-core/core/index.js:268:11)
cube_1   | Refresh Scheduler Error: scheduler-049bcda8-bf1c-4a9c-8d2c-a60c6d4a814e
cube_1   | {}
cube_1   | Error: Cannot convert undefined or null to object
```

**Comment by ovr** [comment]
@benswinburne 

Thank you for submitting an issue!

It's caused while query-orchestrator executes query. It's returns empty results. It's why it's crashing. 

I am working on the fix for that.

**Comment by benswinburne** [comment]
Thanks for the quick fix @ovr . 

Any thoughts on _why_ my preaggregation is looking for a date in the future?

My concern is that the fix, whilst preventing the error just hides what is happening to some degree.

If i leave it running, it repeatedly attempts to get the data for the 15th obviously which it won't find so it's still just querying athena for things which aren't there.

**Comment by ovr** [comment]
@benswinburne 

My solution doesn't work because this will break selection from this table. After code review, I found that it's done only when the driver is used in readOnly mode. 

Anyway It's not possible to detect types from response when it's empty 😄 

Did you use `readOnly` for `athena-driver` and why?

**Comment by benswinburne** [comment]
I had put readOnly on there primarily because of a mistake i'd made initially.

Some misconfiguration (i think i'd missed external:true from my preaggregation) meant that it created a database and some tables in Athena.

Before I worked out why it'd done that i'd put `readOnly: true` onto the Athena driver in an attempt to stop that. Once I worked out i hadn't set `external: true`, i fixed that and left the `readOnly: true` in an attempt to stop that happening in future.

I want my Athena store to be read only so I left the flag set to true thinking i was telling cube that not knowing it'd have any negative effects.

I'll remove readOnly now and see what happens.

**Comment by benswinburne** [comment]
I've removed `readOnly` and it works in terms of not getting an error now _but_ it is still querying into the future. it's created 6 empty tables of future dates

![image](https://user-images.githubusercontent.com/1208977/102135208-8c2c8b00-3e4f-11eb-8dd2-7a843f8691bc.png)

**Comment by ovr** [comment]
@benswinburne Did you send any query with range till 20?

**Comment by benswinburne** [comment]
Nope i haven't sent any queries. I just started the server up and it ran loads of queries itself and filled all my aggregation tables up

**Comment by benswinburne** [comment]
I had a similar problem the other day whereby it created 14 days of data from now()-14 instead of the now()-7 i had configured. I assumed it was me having misconfigured the refreshKey etc.

I'm not entirely sure the configuration i had at the time but i will try and replicate. Seems the math somewhere to work out how many days to do is off perhaps?

**Comment by ovr** [comment]
@benswinburne What datatype is used for `dt`?

**Comment by benswinburne** [comment]
Interestingly, I just wiped the database completely, nuked redis and started fresh on all 3 services.

It created exactly 14 tables. 7th-14th with data, 15th-20th empty obviously.

![image](https://user-images.githubusercontent.com/1208977/102136540-6bfdcb80-3e51-11eb-91f6-902f4f1ebbf5.png)

I just started up the server and ran no queries against it. i can send you the full log from cube if that helps (although i forgot to put log level trace) so it's just `DEBUG_LOG=true` level whatever that is.

```
    dt: {
      sql: `date_parse(dt, '%Y-%m-%d')`,
      type: `time`,
    },
```

In athena it's `{ name: 'dt', type: 'varchar' },`
In the glue catalog it's `partitionKeys: [{ name: 'dt', type: 'string' }],`

**Comment by benswinburne** [comment]
Just noticed that it is creating tables in Athena again, however.

```
const AthenaDriver = require('@cubejs-backend/athena-driver');
const MySqlDriver = require('@cubejs-backend/mysql-driver');

module.exports = {
  driverFactory: () =>
    new AthenaDriver({
      // https://github.com/cube-js/cube.js/issues/1597#issuecomment-744702547
      // readOnly: true,
      accessKeyId: process.env.CUBEJS_AWS_KEY,
      secretAccessKey: process.env.CUBEJS_AWS_SECRET,
      region: process.env.CUBEJS_AWS_REGION,
      S3OutputLocation: process.env.CUBEJS_AWS_S3_OUTPUT_LOCATION,
    }),
  preAggregationsSchema:
    process.env.PRE_AGGREGATIONS_SCHEMA || 'stb_pre_aggregations',
  preAggregationsOptions: {
    queueOptions: {
      concurrency: 5,
    },
  },
  externalDbType: process.env.CUBEJS_EXT_DB_TYPE || 'mysql',
  externalDriverFactory: () =>
    new MySqlDriver({
      host: process.env.CUBEJS_EXT_DB_HOST || '127.0.0.1',
      database: process.env.CUBEJS_EXT_DB_NAME || 'stb_pre_aggregations',
      user: process.env.CUBEJS_EXT_DB_USER,
      password: process.env.CUBEJS_EXT_DB_PASS,
      port: process.env.CUBEJS_EXT_DB_PORT || 3306,
    }),
  orchestratorOptions: {
    rollupOnlyMode: false,
    preAggregationsOptions: {
      queueOptions: {
        concurrency: 5,
      },
    },
  },
  scheduledRefreshTimer: 30,
};
```

This is my Cube.js file which appears to have nothing out of the ordinary in.

**Comment by ovr** [comment]
I am going to close this issue because the original problem was resolved. Thanks

@benswinburne As I understand you resolved the latest issue with dates, yes?
