### ISSUE TITLE
Dremio driver instantiation in multi dataSource approach

### ISSUE THREAD

**Issue by saradharavi** [cube-js/cube.js#1728]
**Describe the bug**
Weird error is thrown when using dremio dataSource in multiple data Sources scenario with postgres and other db source based schemas. 
*To Reproduce*
1. Add an example drem-metrics.js schema with dataSource as dremio_metrics
2. In Index.js override the functions: dbType and driverFactory as mentioned in the docs to conditionally initialize the right driver.
3. Even after declaring the dataSource DREMIO_METRICS in the schema and  checking on it to be overridden to create a DremioDriver in the driverFactory we see an error on making queries to this schema. Looks like the driverFactory method is not even being called, from debug logs.
`[2021-01-05T18:12:54.637Z] [INFO]: dbType: dataSource is default
[2021-01-05T18:12:54.637Z] [INFO]: dbType: databaseType value is postgres
[2021-01-05T18:12:54.639Z] [INFO]: dbType: dataSource is default
[2021-01-05T18:12:54.639Z] [INFO]: dbType: databaseType value is postgres
[2021-01-05T18:12:54.639Z] [INFO]: dbType: dataSource is DREMIO_METRICS
[2021-01-05T18:12:54.639Z] [INFO]: parseDataSource: value for dataSource passed is DREMIO_METRICS
[2021-01-05T18:12:54.639Z] [INFO]: dbType: non-default databaseType value is dremio
[2021-01-05T18:12:54.639Z] [INFO]: dbType: dataSource is DREMIO_METRICS
[2021-01-05T18:12:54.639Z] [INFO]: parseDataSource: value for dataSource passed is DREMIO_METRICS
[2021-01-05T18:12:54.639Z] [INFO]: dbType: non-default databaseType value is dremio
Internal Server Error: 4aab7fb7-f0d1-4228-bbec-4e9ddd56ac95-span-1 (2ms)
--
"{\"measures\":[\"METRICS.total_query_count\"],\"timeDimensions\":[{\"dimension\":\"METRICS.metric_timestamp\",\"granularity\":\"day\",\"dateRange\":\"Last 30 days\"}],\"order\":{}}"
--
{} 
Error: Unknown dbType for 'DREMIO_METRICS' data source: postgres
    at CompilerApi.getSql (/foo/cubejs/node_modules/@cubejs-backend/server-core/core/CompilerApi.js:78:15)
    at async Promise.all (index 0)
    at async ApiGateway.dryRun (/foo/cubejs/node_modules/@cubejs-backend/api-gateway/dist/src/gateway.js:367:32)
    at async /foo/cubejs/node_modules/@cubejs-backend/api-gateway/dist/src/gateway.js:270:13
   `
**Expected behavior**
Expecting a DremioDriver being created in the driverFactory method instead of defaulting to postgres (or maybe th eerror is misleading)

**Screenshots**

**Version:**
"@cubejs-backend/dremio-driver": "^0.25.2"
"@cubejs-backend/server": "^0.25.3"

**Additional context**

**Comment by saradharavi** [comment]
Most probable reason is null assignment at https://github.com/cube-js/cube.js/blob/master/packages/cubejs-schema-compiler/adapter/QueryBuilder.js#L39 that is caused from the ADAPTERS list not having dremio. The error cascades to dialectFactory  and the query for the dataSource of dbType dremio fails.
