### ISSUE TITLE
What are the exact steps to integrate a non built-in DB into Cube

### ISSUE THREAD

**Issue by klausb** [cube-js/cube.js#1797]
**Please describe the exacts steps to configure access to a foreign DB type**

**Problem**
I try to integrate  a Vertica driver into Cube.js.
It worked with an older version, but fails now. 
It looks like I miss some steps.

I start the server like this

```
const server = new CubejsServer({
  driverFactory: ({ dataSource }) => new VerticaDriver({ database: dataSource })
});
```

But Cube fails inside the scheduler code and shows an error in the UI.

In .env Vertica is specified specified:
`CUBEJS_DB_TYPE=vertica`

My driver looks like this

```
const vertica = require('vertica');
const SqlString = require('sqlstring');
const BaseDriver = require('@cubejs-backend/query-orchestrator/driver/BaseDriver');

const { zipObj, prop } = require('ramda');

const applyParams = (query, params) => {
  return SqlString.format(query, params);
};

class VerticaDriver extends BaseDriver {

  constructor(config) {
    super();
    this.config = config || {};
    this.verticaConnection = vertica.connect({
      host: process.env.CUBEJS_DB_HOST,
      database: process.env.CUBEJS_DB_NAME,
      port: process.env.CUBEJS_DB_PORT,
      user: process.env.CUBEJS_DB_USER,
      password: process.env.CUBEJS_DB_PASS,
      ssl: false
    }, err => {
      if (err) {
        console.log(`Cannot connect to vertica: ${err}`);
      }
    });
    //this.verticaConnection.debug = true;
  }

  async query(query, values) {
    let qstr = applyParams(query, values);
    // qstr = qstr.replace(/'{/g, '');
    // qstr = qstr.replace(/}'/g, '');
    // qstr = qstr.replace(/["]/g, () => '\'');
    console.log(qstr);
    return await this.queryResponse(qstr);
  }

  queryResponse(query) {
    return new Promise((resolve, reject) => {
      const res = this.verticaConnection.query(query, (err, rs) => {
        if (err) {
          reject(err);
        } else {
          resolve(rs.rows.map(row => zipObj(rs.fields.map(prop('name')), row)));
        }
      });
    });
  }


  async testConnection() {
    try {
      return await this.query('SELECT ?::int AS number', ['1']);
    } catch (e) {
      throw e;
    }
  }

  informationSchemaQuery() {
    return `select column_name,
             table_name, 
             table_schema,
             data_type
       from columns
       where table_schema = 'mf_shared_provider_default'
       order by table_schema, table_name`;
  }

  downloadQueryResults() {
    throw new Error('Not implemented');
  }

  readOnly() {
    return true;
  }

  /*
  tablesSchema() {
    const query = this.informationSchemaQuery();
 
    const reduceCb = (result, i) => {
      let schema = (result[i.table_schema] || {});
      let tables = (schema[i.table_name] || []);
 
      tables.push({ name: i.column_name, type: i.data_type, attributes: i.key_type ? ['primaryKey'] : [] });
 
      tables.sort();
      schema[i.table_name] = tables;
      schema = sortByKeys(schema);
      result[i.table_schema] = schema;
 
      return sortByKeys(result);
    };
 
    return this.query(query).then(data => reduce(reduceCb, {}, data));
  }
  */

  createSchemaIfNotExists(schemaName) {
    console.log('createSchemaIfNotExists not supported');
    return {};
  }

  getTablesQuery(schemaName) {
    return this.query(
      `SELECT table_name FROM tables WHERE table_schema = ${this.param(0)}`,
      [schemaName]
    );
  }

  loadPreAggregationIntoTable(preAggregationTableName, loadSql, params, tx) {
    return this.query(loadSql, params, tx);
  }

  dropTable(tableName, tx) {
    console.log('dropTable not supported');
    return {};
  }

  param(/* paramIndex */) {
    return '?';
  }

  testConnectionTimeout() {
    return 10000;
  }

  async downloadTable(table) {
    return { rows: await this.query(`SELECT * FROM ${table}`) };
  }

  async uploadTable(table, columns, tableData) {
    console.log('uploadTable not supported');
  }

  toColumnValue(value, genericType) {
    return value;
  }

  async tableColumnTypes(table) {
    const [schema, name] = table.split('.');
    const columns = await this.query(
      `select column_name,
            table_name, 
            table_schema,
            data_type
        from columns
        where table_schema = 'opsbridge_store' AND table_name = ${this.param(0)} AND table_schema = ${this.param(1)}`,
      [name, schema]
    );
    return columns.map(c => ({ name: c.column_name, type: this.toGenericType(c.data_type) }));
  }

  createTable(quotedTableName, columns) {
    return this.query(this.createTableSql(quotedTableName, columns), []);
  }

  createTableSql(quotedTableName, columns) {
    columns = columns.map(c => `${this.quoteIdentifier(c.name)} ${this.fromGenericType(c.type)}`);
    return `CREATE TABLE ${quotedTableName} (${columns.join(', ')})`;
  }

  toGenericType(columnType) {
    return DbTypeToGenericType[columnType.toLowerCase()] || columnType;
  }

  fromGenericType(columnType) {
    return columnType;
  }

  quoteIdentifier(identifier) {
    return `"${identifier}"`;
  }
}

module.exports = VerticaDriver;

```

**Comment by klausb** [comment]
Additional info:
I can't find a way to plug to the schema compiler with my connector.

Maybe there is no way to extend cube.js by a new DB just by plugins, but only by submitting a PR.
Please clarify.

I also tried jdbc, because there is an official jdbc driver, but the creation of a new project with jdbc support fails in the create command with this:

```
- Installing JDBC dependencies

Cube.js Error ---------------------------------------

Error: Cannot find module 'jdbc/lib/drivermanager'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/mnt/c/work/cubejs/vertica/node_modules/@cubejs-backend/jdbc-driver/driver/JDBCDriver.js:10:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by ovr** [comment]
Hello @klausb,

Sorry for late reply.

> But Cube fails inside the scheduler code and shows an error in the UI.

What error do you get?

Generally, your driver didn't implement `dialectClass` for `VerticaQuery`, do you use `dialectFactory` to get it works?

Example: https://github.com/cube-js/cube.js/blob/v0.25.21/packages/cubejs-druid-driver/src/DruidDriver.ts#L14

Are you interested to submit a PR with implementation for `VerticaDriver`?

> I also tried jdbc, because there is an official jdbc driver, but the creation of a new project with jdbc support fails in the create command with this:

It's outdated.

**Comment by paveltiunov** [comment]
Please see https://github.com/cube-js/cube.js/blob/master/CONTRIBUTING.md#implementing-a-driver
