### ISSUE TITLE
Node 14 Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency

### ISSUE THREAD

**Issue by rongfengliang** [cube-js/cube.js#1798]
**Describe the bug**
(node:18667) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
links https://github.com/antlr/antlr4/issues/2834 ,  

**Screenshots**
node --trace-warnings  ./node_modules/.bin/cubejs-server
```code
warning You are using two different lock files, both for npm/yarn. Please use only one.
🔒 Your temporary cube.js token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTA5NTYxMzcsImV4cCI6MTYxMTA0MjUzN30.7Vez0jJ7QvQnzfU6kQ7zRjShHE-O6_CMlKwmOJvlbvQ
🦅 Dev environment available at http://localhost:4000
🚀 Cube.js server (0.25.20) is listening on 4000
(node:18667) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:814:11)
    at Object.get (internal/modules/cjs/loader.js:825:5)
    at Object.<anonymous> (/Users/dalong/mylearning/cubejs-source/cubestorage-app/pre-age/node_modules/@cubejs-backend/schema-compiler/node_modules/antlr4/RuleContext.js:30:46)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/dalong/mylearning/cubejs-source/cubestorage-app/pre-age/node_modules/@cubejs-backend/schema-compiler/node_modules/antlr4/PredictionContext.js:8:19)
(node:18667) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:814:11)
    at Object.get (internal/modules/cjs/loader.js:825:5)
    at Object.<anonymous> (/Users/dalong/mylearning/cubejs-source/cubestorage-app/pre-age/node_modules/@cubejs-backend/schema-compiler/node_modules/antlr4/tree/Trees.js:13:49)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/dalong/mylearning/cubejs-source/cubestorage-app/pre-age/node_modules/@cubejs-backend/schema-compiler/node_modules/antlr4/RuleContext.js:122:13)
```
**Version:**
[e.g. 0.25.20] 

@cubejs-backend/schema-compiler

**Comment by ovr** [comment]
Hello @rongfengliang,

It's caused by `anltr4` library, and it's just warning not an error. They prepared a new version with a fix for that by rewriting runtime for js, but it started to require Node.js 14 as a minimal Node.js version.

refs https://github.com/antlr/antlr4/issues/2970

I am still thinking how to resolve this issue.
