### ISSUE TITLE
Pre-aggregation queries are not GTID safe - MySQL

### ISSUE THREAD

**Issue by MattGson** [cube-js/cube.js#1810]
**Describe the bug**

Queries to create pre-agg tables use ` CREATE TABLE ... SELECT ` syntax. 
This syntax is not valid when running MySQL with GTID based replication. [see here](https://dev.mysql.com/doc/refman/5.6/en/replication-gtids-restrictions.html)

GTID based replication also happens to be used by Google CloudSQL and is not configurable.
This means that pre-aggregations cannot by used.

Note: This issue theoretically will also appear when using statement based replication.

**To Reproduce**
[Run a MySQL database using GTIDs for replication](https://dev.mysql.com/doc/refman/5.6/en/replication-gtids-howto.html)

Add a cube with a pre-aggregation.
Will fail with an error like `"Error: ER_GTID_UNSAFE_CREATE_SELECT: Statement violates GTID consistency: CREATE TABLE ... SELECT."`

**Expected behavior**
Pre-aggregation queries should be safe for statement based replication as well as replication with GTIDs.

**Comment by ovr** [comment]
Hello @MattGson ,

Yes, Its known limitation. You can pass `loadPreAggregationWithoutMetaLock` option directly to the `MysqlDriver` and it will use another strategy with two queries to skip this limitation.

Does it work for you?

Thanks

**Comment by MattGson** [comment]
@ovr This doesn't seem to fix the issue:

Driver setup:
```
const server = new CubejsServer({
    apiSecret: 'my-secret',
    dbType: 'mysql',
    driverFactory: () =>
        new MySqlDriver({
            ...my-config,
            loadPreAggregationWithoutMetaLock: true,
        }),
...
```

Getting following error still:

```
{
	"message": "Error while querying",
	"processingId": "7",
	"queueSize": 3,
	"duration": 26,
	"queryKey": [
		["CREATE TABLE agg_122_checkins.ch_main AS SELECT CI.*, \n       ... ", [122]],
		[
			[{
				"FLOOR((UNIX_TIMESTAMP()) / 60)": 26853056
			}]
		]
	],
	"queuePrefix": "SQL_PRE_AGGREGATIONS_app_id_122_73_checkins_default",
	"requestId": "283d1451-f1a8-4c5a-bf09-66b7755519d7-span-1",
	"timeInQueue": 8,
	"error": "Error: ER_GTID_UNSAFE_CREATE_SELECT: Statement violates GTID consistency: CREATE TABLE ... SELECT.\n    at Query.Sequence._packetToError (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)\n    at Query.ErrorPacket (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)\n    at Protocol._parsePacket (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)\n    at Parser._parsePacket (/usr/src/app/node_modules/mysql/lib/protocol/Parser.js:433:10)\n    at Parser.write (/usr/src/app/node_modules/mysql/lib/protocol/Parser.js:43:10)\n    at Protocol.write (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (/usr/src/app/node_modules/mysql/lib/Connection.js:91:28)\n    at Socket.<anonymous> (/usr/src/app/node_modules/mysql/lib/Connection.js:525:10)\n    at Socket.emit (events.js:314:20)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    --------------------\n    at Protocol._enqueue (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)\n    at Connection.query (/usr/src/app/node_modules/mysql/lib/Connection.js:201:25)\n    at internal/util.js:297:30\n    at new Promise (<anonymous>)\n    at Connection.bound query [as execute] (internal/util.js:296:12)\n    at /usr/src/app/node_modules/@cubejs-backend/mysql-driver/driver/MySqlDriver.js:122:22\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async /usr/src/app/node_modules/@cubejs-backend/mysql-driver/driver/MySqlDriver.js:150:9\n    at async PreAggregationLoader.refreshImplStoreInSourceStrategy (/usr/src/app/node_modules/@cubejs-backend/server-core/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/PreAggregations.js:396:9)"
}
```

**Comment by vkruoso** [comment]
Just tried the same on the latest release, and I still get the same issue.

**Comment by paveltiunov** [comment]
@MattGson @vkruoso I can confirm GTID consistency MySQL mode isn't supported. Using Cube Store with the read-only MySQL driver mode is the only solution for now.
