### ISSUE TITLE
rollupOnlyMode throws exceptions about queries used to determine scheduled refresh timings

### ISSUE THREAD

**Issue by benswinburne** [cube-js/cube.js#1828]
**Describe the bug**

When using custom refreshRangeStart and refreshRangeEnd to generate queries used to determine the ranges in combination with `orchestratorOptions.rollupOnlyMode: false` the logs fill up rapidly with exceptions "No pre-aggregation exists for that query". For obvious reasons there never will be.

```
Jan 18 14:24:35 ip-172... web: {"message":"Error querying db","query":"SELECT to_iso8601(NOW() - interval '90' day)","params":[],"error":"Error: No pre-aggregation exists for that query\n    at /var/app/current/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/QueryOrchestrator.js:37:23"}
Jan 18 14:24:35 ip-172... web: {"message":"Error querying db","query":"SELECT to_iso8601(NOW())","params":[],"error":"Error: No pre-aggregation exists for that query\n    at /var/app/current/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/QueryOrchestrator.js:37:23"}
Jan 18 14:24:35 ip-172... web: {"message":"Error querying db","query":"SELECT to_iso8601(NOW() - interval '7' day)","params":[],"error":"Error: No pre-aggregation exists for that query\n    at /var/app/current/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/QueryOrchestrator.js:37:23"}
Jan 18 14:24:35 ip-172... web: {"message":"Error querying db","query":"SELECT to_iso8601(NOW())","params":[],"error":"Error: No pre-aggregation exists for that query\n    at /var/app/current/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/QueryOrchestrator.js:37:23"}
Jan 18 14:24:35 ip-172... web: {"message":"Error querying db","query":"SELECT to_iso8601(NOW() - interval '7' day)","params":[],"error":"Error: No pre-aggregation exists for that query\n    at /var/app/current/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/QueryOrchestrator.js:37:23"}
Jan 18 14:24:35 ip-172... web: {"message":"Error querying db","query":"SELECT to_iso8601(NOW())","params":[],"error":"Error: No pre-aggregation exists for that query\n    at /var/app/current/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/QueryOrchestrator.js:37:23"}
Jan 18 14:24:35 ip-172... web: {"message":"Refresh Scheduler Error","error":"Error: No pre-aggregation exists for that query","requestId":"scheduler-94f2dbdc-948d-442d-ad36-083fc9b225d4"}
```

The `SELECT 1` query does it too, but that was fixed in 0.25.20.

```
Jan 18 14:24:35 ip-172... web: {"message":"Error querying db","query":"SELECT 1","error":"Error: No pre-aggregation exists for that query\n    at /var/app/current/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/QueryOrchestrator.js:37:23","requestId":"scheduler-94f2dbdc-948d-442d-ad36-083fc9b225d4"}
```

**To Reproduce**
1. Make a preAggregation with the following refresh configuration.

```
      refreshKey: {
        every: '15 1 * * *', // at 01:15 every day
        timezone: 'Europe/London',
        incremental: true,
        updateWindow: `7 day`,
      },
      scheduledRefresh: true,
      refreshRangeStart: {
        sql: `SELECT to_iso8601(NOW() - interval '7' day)`,
      },
      refreshRangeEnd: {
        sql: `SELECT to_iso8601(NOW())`,
      },
```

2. Enable rollupOnlyMode

```
  orchestratorOptions: {
    rollupOnlyMode: true,
  },
```

3. Run server
4. See exceptions in logs as it builds tables

**Expected behavior**
Only block queries run to get data, not ones cube uses internally to coordinate timings etc.

**Version:**
0.25.21
(and as far back as 0.24.6 at least)

**Comment by jcw-** [comment]
Using just this option on its own (and not in combination with `externalRefresh`) does appear to be broken, doh.

Thinking about it, I believe what's needed is to detect the difference between an internal query or not and don't try and apply the rollup-only condition to internal queries.

Currently, internal queries are calling `executeQuery` on the OrchestratorApi which then calls `fetchQuery` which always does the rollup-only enforcement.

**Comment by benswinburne** [comment]
Thanks @jcw- unfortunately there isn't enough need to split out workers and api instances at the moment in our use case yet so I've just turned `rollupOnlyMode` off for now but I'll bear this configuration in mind if I change the how it's deployed before the bug fix.

**Comment by paveltiunov** [comment]
`CUBEJS_ROLLUP_ONLY=true` should be used in order to solve this problem. Learn more here https://cube.dev/docs/caching/using-pre-aggregations#rollup-only-mode
