### ISSUE TITLE
QueryQueue UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by root-io** [cube-js/cube.js#1873]
**Describe the bug**

I run CubejsServerCore with express and node (no docker) and I get some warning just after opening my frontend.

```
Performing query: scheduler-1295124a-4c64-4d08-b8cc-863de66fb12e
Executing SQL: scheduler-1295124a-4c64-4d08-b8cc-863de66fb12e
--
  SELECT FLOOR((EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)) / 120)
--
(node:14497) UnhandledPromiseRejectionWarning: Error: Continue wait
    at QueryQueue.executeInQueue (/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/QueryQueue.js:82:23)
(node:14497) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14497) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:14497) UnhandledPromiseRejectionWarning: Error: Continue wait
    at QueryQueue.executeInQueue (/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/QueryQueue.js:82:23)
(node:14497) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14497) UnhandledPromiseRejectionWarning: Error: Continue wait
    at QueryQueue.executeInQueue (/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/QueryQueue.js:82:23)
(node:14497) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:14497) UnhandledPromiseRejectionWarning: Error: Continue wait
    at QueryQueue.executeInQueue (/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/QueryQueue.js:82:23)
(node:14497) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
Performing query completed: scheduler-1295124a-4c64-4d08-b8cc-863de66fb12e (5660ms)
```

The code that raised the warning

```
            result = await redisClient.getResultBlocking(queryKey);
            if (!result) {
                throw new ContinueWaitError_1.ContinueWaitError();
            }
```

I am running the cubejs backend with the env var `CUBEJS_CACHE_AND_QUEUE_DRIVER=memory` and no redis running.

**Version:**
@cubejs-backend/server-core 0.25.26
@cubejs-backend/snowflake-driver 0.25.26
Node.js 14.15.4

**Comment by ovr** [comment]
@root-io Can you provide more details & logs? What query was executed?

> at QueryQueue.executeInQueue (/node_modules/@cubejs-backend/query-orchestrator/dist/src/orchestrator/QueryQueue.js:82:23)

It doesn't contain source-maps and looks like you don't use official docker image, How do you start your server?

Thanks

**Comment by root-io** [comment]
Hey @ovr sorry for the lack of details, I just updated the issue, ping me if you need more

**Comment by craigbeck** [comment]
Same here:
1. using `memory` store locally (so no Redis)
2. not using official docker image
3. only when running with `CUBEJS_SCHEDULED_REFRESH_TIMER=true`

**Comment by ovr** [comment]
@root-io @craigbeck Can you try with the `v0.26.12` release? Does it fix the issue?

Thanks

**Comment by craigbeck** [comment]
Looks good from this end :+1: been running locally for 30+ minutes with and without scheduler and no `UnhandledPromiseRejection` issues logged (usually would see them start in first few minutes, then continue regularly)

**Comment by root-io** [comment]
Same, no warning anymore thanks!
