### ISSUE TITLE
Error on add to Dashboard option

### ISSUE THREAD

**Issue by alokthakur142** [cube-js/cube.js#2041]
**Describe the bug**
```TypeError: Cannot read property 'get' of undefined
    at JSXOpeningElement (D:\Experiment\cubejs\br3\node_modules\.tmp\cubejs-playground-templates-master\node_modules\@cubejs-templates\core\src\ChartSnippet.js:34:13)
    at NodePath._call (D:\Experiment\cubejs\br3\node_modules\.tmp\cubejs-playground-templates-master\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (D:\Experiment\cubejs\br3\node_modules\.tmp\cubejs-playground-templates-master\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (D:\Experiment\cubejs\br3\node_modules\.tmp\cubejs-playground-templates-master\node_modules\@babel\traverse\lib\path\context.js:92:31)
    at TraversalContext.visitQueue (D:\Experiment\cubejs\br3\node_modules\.tmp\cubejs-playground-templates-master\node_modules\@babel\traverse\lib\context.js:116:16)
    at TraversalContext.visitSingle (D:\Experiment\cubejs\br3\node_modules\.tmp\cubejs-playground-templates-master\node_modules\@babel\traverse\lib\context.js:85:19)
    at TraversalContext.visit (D:\Experiment\cubejs\br3\node_modules\.tmp\cubejs-playground-templates-master\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (D:\Experiment\cubejs\br3\node_modules\.tmp\cubejs-playground-templates-master\node_modules\@babel\traverse\lib\index.js:82:17)
    at NodePath.visit (D:\Experiment\cubejs\br3\node_modules\.tmp\cubejs-playground-templates-master\node_modules\@babel\traverse\lib\path\context.js:99:18)
    at TraversalContext.visitQueue (D:\Experiment\cubejs\br3\node_modules\.tmp\cubejs-playground-templates-master\node_modules\@babel\traverse\lib\context.js:116:16)
```

**To Reproduce**
1. Go to 'Server Playground'
2. Choose graph and components and Click on 'Add to Dashboard'
3. See error

**Comment by vasilev-alex** [comment]
@alokthakur142 should be fixed in `v0.26.11`
