### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined at ChartSnippet.js:34:14 while trying to add a chart to dashboard with the "Add to Dashboard" button

### ISSUE THREAD

**Issue by thecodelearner** [cube-js/cube.js#2367]
**Describe the bug**
This error comes up when we try to build a chart in the Cubejs Playground and then hit the "Add to Dashboard" button.

Stack trace:

`TypeError: Cannot read property 'get' of undefined
    at JSXOpeningElement (/home/sahil/code/rdash/hello-world/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@cubejs-templates/core/src/ChartSnippet.js:34:13)
    at NodePath._call (/home/sahil/code/rdash/hello-world/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/sahil/code/rdash/hello-world/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/home/sahil/code/rdash/hello-world/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/home/sahil/code/rdash/hello-world/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@babel/traverse/lib/context.js:116:16)
    at TraversalContext.visitSingle (/home/sahil/code/rdash/hello-world/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@babel/traverse/lib/context.js:85:19)
    at TraversalContext.visit (/home/sahil/code/rdash/hello-world/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/home/sahil/code/rdash/hello-world/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/home/sahil/code/rdash/hello-world/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@babel/traverse/lib/path/context.js:99:18)
    at TraversalContext.visitQueue (/home/sahil/code/rdash/hello-world/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@babel/traverse/lib/context.js:116:16)
Collapse`

**Potential Issue**

**After digging into the `/cubejs-playground-templates-master/node_modules/@cubejs-templates/core/package.json` file, we see that the `@cubejs-templates/core package` is still at v0.0.3 when the latest is v0.0.5**

**Things we've tried:**
1. `rm -rf /cubenew/node_modules/.tmp` and then "Add to Dashboard" again

**Version:**
"@cubejs-backend/server": "^0.26.56"
"@cubejs-client/core": "^0.26.55"

**Dashboard-app Version**
"@cubejs-client/core": "^0.26.55"
"@cubejs-client/react": "^0.26.55"
"@cubejs-templates/core": "^0.0.5"

cc @vasilev-alex

**Comment by vasilev-alex** [comment]
Thanks @thecodelearner!
