### ISSUE TITLE
TypeError: this.logger is not a function

### ISSUE THREAD

**Issue by root-io** [cube-js/cube.js#2431]
**Describe the bug**

It crash just after start. I can give more details if needed.

```
/node_modules/@cubejs-backend/server-core/dist/src/core/server.js:262
                this.logger('Cube Store is not supported on your system', {
                     ^

TypeError: this.logger is not a function
    at CubejsServerCore.handleConfiguration (/node_modules/@cubejs-backend/server-core/dist/src/core/server.js:262:22)
    at new CubejsServerCore (/node_modules/@cubejs-backend/server-core/dist/src/core/server.js:98:29)
    at Function.create (/node_modules/@cubejs-backend/server-core/dist/src/core/server.js:343:16)
    at file:///src/index.js:21:18
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Version:**
@cubejs-backend/postgres-driver 0.26.65
@cubejs-backend/server-core 0.26.65
@cubejs-backend/snowflake-driver 0.26.65
Node.js 14.16.0
macOS 11 (Big Sur)

**Additional context**
I run CubejsServerCore with express and node (no docker)

**Comment by root-io** [comment]
Thanks :)

**Comment by ovr** [comment]
Thank you @root-io for bug reporting, It's was my miss in the latest release.
