### ISSUE TITLE
Error during Postgres Pre-Aggregation Creation: type "varbinary" does not exist

### ISSUE THREAD

**Issue by blefevre** [cube-js/cube.js#2450]
**Describe the bug**
When creating a Postgres pre-aggregation table from an AWS Athena DB any usage of `countDistinctApprox` will cause the pre-aggregation to fail as `varbinary` doesn't exist in Postgres.

**To Reproduce**
Use AWS Athena as the source DB and Postgres for external preaggregations.
Create a measure that uses `countDistinctApprox`.
Create a pre-aggregation that uses the measure.

**Expected behavior**
The pre-aggregation is created successfully.

**Log**
```
error: Error during create table: CREATE TABLE pre_aggregations_dev.v_v220210201_2amccsph_1mwby0wc_1g61d1r (<removed>, "v__count" varbinary): type "varbinary" does not exist
    at Parser.parseErrorMessage (/Users/<removed>/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/Users/<removed>/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/Users/<removed>/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (/Users/<removed>/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Version:**
```
"@cubejs-backend/athena-driver": "^0.26.69",
"@cubejs-backend/mysql-driver": "^0.26.69",
"@cubejs-backend/postgres-driver": "^0.26.69",
"@cubejs-backend/server": "^0.26.71",
```

**Comment by blefevre** [comment]
I managed to resolve this by adding the conversion to the Postgres driver:
```js
// cube.js/packages/cubejs-postgres-driver/driver/PostgresDriver.js:8
const GenericTypeToPostgres = {
  string: 'text',
  double: 'decimal',
  varbinary: 'bytea',
};
```

However Athena (Presto) and Postgres use different HyperLogLog formats, Dense v2 and Dense v1 respectively.
Due to this table creation still fails with `Error: unknown schema version 3`.
With no access to add or change the extensions in Athena or RDS this incompatibility is impossible to resolve.
