### ISSUE TITLE
error while trying to create a dashboard app

### ISSUE THREAD

**Issue by Daniel0205** [cube-js/cube.js#2454]
**Describe the bug**

**To Reproduce**
1. Go to dashboard app on cubejs playground
2. Click on any of the options to autogrenerate an app
4. See the folowing error:
```
/home/daniel/Escritorio/api/node_modules/.tmp/cubejs-playground-templates-master/packages/templates-core/src/VueSourceSnippet.js:8
  scriptSource = null;
               ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/daniel/Escritorio/api/node_modules/.tmp/cubejs-playground-templates-master/packages/templates-core/src/TemplatePackage.js:8:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

```
**Expected behavior**
Creates the react dashboard normally

**Screenshots**
![image](https://user-images.githubusercontent.com/24316482/112796375-838f4780-902f-11eb-8631-917b39c85d20.png)

**Version:**
 ```
"devDependencies": {
    "@cubejs-backend/cubestore-driver": "^0.26.71",
    "@cubejs-backend/postgres-driver": "^0.26.69",
    "@cubejs-backend/server": "^0.26.71"
  },
  "dependencies": {
    "@cubejs-client/core": "^0.26.70",
    "@cubejs-client/ngx": "^0.26.61",
    "@cubejs-client/react": "^0.26.70",
    "@cubejs-client/vue": "^0.26.70"
  }
```

**Additional context**
Some days ago it creates the react dashboard normally but then I reinstalled and it didnt work again.

**Comment by vasilev-alex** [comment]
hi @Daniel0205! Which node version are you using?

**Comment by blavonne** [comment]
I have the same problem

**Comment by Daniel0205** [comment]
v10.19.0

**Comment by sveisvei** [comment]
@Daniel0205 Node 10 is about 3 years old and even not supported anymore after next month, ref https://nodejs.org/en/about/releases/.

**Comment by Daniel0205** [comment]
@sveisvei @vasilev-alex @blavonne I upgrade my node version and it worked. Thanks!

**Comment by vasilev-alex** [comment]
Should work for node 10 now too

**Comment by blavonne** [comment]
@sveisvei yeah, it's so old. But I used LMDE (debian) and there was only 10 version nodejs without any options to update. Seems like it is Ubuntu time :)))
@vasilev-alex thank you :)
