### ISSUE TITLE
Support HAVING in queries

### ISSUE THREAD

**Issue by jdrake** [cube-js/cube.js#2653]
**Is your feature request related to a problem? Please describe.**
I want to be able to filter query results based on an aggregation.

**Describe the solution you'd like**
This would involve adding support for the `HAVING` clause, e.g. `HAVING sum(customer_count) > 100`. 

**Describe alternatives you've considered**
N/A

**Additional context**
Stacktrace: 
```
Error querying db: {"query":"SELECT `c_u_s_t_o_m_e_r__c_mktsegment` `c_u_s_t_o_m_e_r__c_mktsegment`, sum(`c_u_s_t_o_m_e_r__count`) `c_u_s_t_o_m_e_r__count` FROM dev_pre_aggregations.c_u_s_t_o_m_e_r_customers_by_market_segment AS `c_u_s_t_o_m_e_r__customers_by_market_segment` GROUP BY 1 HAVING (sum(`c_u_s_t_o_m_e_r__count`) > ?) ORDER BY 2 DESC LIMIT 10000","params":["10"],"error":"Error: Internal: This feature is not implemented: HAVING is not implemented yet\ndisabled backtrace\n    at QueryQueue.parseResult (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:101:13)\n    at QueryQueue.executeInQueue (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:90:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at /cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:330:17\n    at QueryOrchestrator.fetchQuery (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:88:20)\n    at OrchestratorApi.executeQuery (/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:40:20)\n    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:557:26\n    at async Promise.all (index 0)\n    at ApiGateway.load (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:543:23)\n    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:242:7","requestId":"9946031f-7e3d-4b7c-a92e-b040f29274b2-span-1"}
Orchestrator error: {"query":{"measures":["CUSTOMER.count"],"timeDimensions":[],"order":{"CUSTOMER.count":"desc"},"dimensions":["CUSTOMER.cMktsegment"],"filters":[{"member":"CUSTOMER.count","operator":"gt","values":["10"]}]},"error":"Error: Internal: This feature is not implemented: HAVING is not implemented yet\ndisabled backtrace","duration":31,"securityContext":{"iat":1620147814},"requestId":"9946031f-7e3d-4b7c-a92e-b040f29274b2-span-1"}
```

**Comment by starsuit** [comment]
🙋  I'm having the same issue

**Comment by paveltiunov** [comment]
@jdrake @starsuit Thanks for raising a hand here! We've already started to work on it.

**Comment by manishgadhock-monotype** [comment]
+1 waiting for this feature

**Comment by ilya-biryukov** [comment]
Fixed in https://github.com/cube-js/cube.js/commit/a020c070cea053983ccd28c5d47e3f805364b713
