### ISSUE TITLE
CubeStore crashes while pre-aggregating to external Postgres DB or CubeStore

### ISSUE THREAD

**Issue by jmadan** [cube-js/cube.js#2825]
Datasource: BigQuery
External Aggregation DB: Postgres
DataSource Size: 64GB approx
Query data size as per big query: 16GB approx

Pre-aggregation process goes on for good 15 minutes and then it crashes all of a sudden with the following error

`Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:475:28)
    at Connection.emit (node:events:369:20)
    at Socket.<anonymous> (/node_modules/pg/lib/connection.js:108:12)
    at Socket.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)`

Postgres logs don't show any error or spike in Memory or CPU utilisation

Bumping up allocated memory to CubeJs node process also does not seem to have any impact on performance or speed of aggregation

PreAggregation definition 

`main: {
        type: `rollup`,
        external: true,
        measureReferences: [
          sumOfTimeInSeconds,  //type SUM 
          views,                              // type COUNT 
          measuredViews,            // type COUNT
        ],
        dimensionReferences: [userId, pageId, pageName, domain],
        timeDimensionReference: timestamp,
        granularity: `day`,
        partitionGranularity: `week`,
        scheduledRefresh: true,
        refreshKey: {
          every: "1 day",
          incremental: true,
          updateWindow: `7 day`,
        },
      },`

**Expected behavior**
Preaggregation to happen without any errors 

**Version:**
@cubejs-backend/api-gateway - 0.27.15
@cubejs-backend/bigquery-driver - 0.27.16
@cubejs-backend/postgres-driver - 0.27.16
@cubejs-backend/server - 0.27.16

**Additional context**
I have tried playing with Granularity (day or week or month) it still crashes
Switching the same to CubeStore produces the following error

`{"error":"Error: Internal: This feature is not implemented: Physical plan does not support logical expression SUM(#e_s__page_name_domain.e_s__measured_views)\ndisabled backtrace"}`

**Comment by paveltiunov** [comment]
Hey @jmadan ! Most likely you need to setup `CUBEJS_DB_BQ_EXPORT_BUCKET` and use it together with Cube Store. Postgres doesn't support it. Please see https://cube.dev/docs/connecting-to-the-database#notes-google-big-query.

**Comment by jmadan** [comment]
@paveltiunov thanks for getting on this but the reason for choosing external pre-aggregation is to query BigQuery less often... with CubeStore and GCP Bucket....I would be constantly hitting BigQuery for every query.

**Comment by keydunov** [comment]
Hey @jmadan,

When you are using Cube Store queries don't hit the source database. They hit the aggregated data from Cube Store instead. 

The bucket @paveltiunov mentioned above is used to export data from BigQuery and load it into the Cube Store in the background during either creation or refresh of the pre-aggregations.
