### ISSUE TITLE
Preaggregation table could not be found when queries are made. (postgres backend)

### ISSUE THREAD

**Issue by saradharavi** [cube-js/cube.js#2855]
**Describe the bug**
The preaggregation table for the postgres based schema are missing in some cases. and when attempting to query we see the following error message in the cubejs logs.
error: table "downmet_main20210527_c10ro1io_punrmxgc_1gb2ogu" does not exist
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.stream.on (/app/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**To Reproduce**
1. Create a schema file with postgres backend 
2. Add a preaggregation on the originalSql  (not rollup)
3. Run the server and issue some queries to the schema having the preagg and let the server run for some time.

**Expected behavior**
Not expect to see the table for preagg missing when other tables with similar date string on the same cube with more or less same number of letters in table name are created and maintained.
**Screenshots**
<img width="1460" alt="Screen Shot 2021-05-28 at 3 38 11 PM" src="https://user-images.githubusercontent.com/38230019/120048089-0e0e0c00-bfcb-11eb-81dd-6f9814e42bda.png">

**Version:**
0.26.56

**Additional context**
The preaggregation schema name is a custom one and schema_name.table_name sometimes exceeds the 64 bytes limit in postgres. table_name alone is well within the limit.
Also there are around 1700 tables in the preaggregation schema.Multiple tables for each day with random hash strings are common.

**Comment by HJ29** [comment]
Not sure the error i encountered is same.
I am using bigquery for db and external preaggregation db.
I only configure originalSql preaggregation, no rollup for now.
```
Error: Not found: Table feedme-253402:dev_pre_aggregations.bills_original_05vaxr5b_qom4txkb_1gco655 was not found in location asia-southeast1
```
I get this error sometime, looks like it tries to query a preaggregation table which doesn't exist. 
i can't find a clear pattern how it happens.
