### ISSUE TITLE
TypeError: oldLogger is not a function

### ISSUE THREAD

**Issue by joshhubers** [cube-js/cube.js#2940]
**Describe the bug**
I just updated a project to version `0.27.30` from `0.23.14`

On startup I get the following exception:

```
(node:8461) UnhandledPromiseRejectionWarning: TypeError: oldLogger is not a function
    at CubejsServerCore.logger (/Users/joshhubers/Code/project/metrics/node_modules/@cubejs-backend/server-core/src/core/server.ts:234:9)
    at RefreshScheduler.runScheduledRefresh (/Users/joshhubers/Code/project/metrics/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:156:21)
    at CubejsServerCore.runScheduledRefresh (/Users/joshhubers/Code/project/metrics/node_modules/@cubejs-backend/server-core/src/core/server.ts:785:39)
    at /Users/joshhubers/Code/project/metrics/node_modules/@cubejs-backend/server-core/src/core/server.ts:773:19
    at Array.map (<anonymous>)
    at CubejsServerCore.handleScheduledRefreshInterval (/Users/joshhubers/Code/project/metrics/node_modules/@cubejs-backend/server-core/src/core/server.ts:766:33)
    at Timeout._onTimeout (/Users/joshhubers/Code/project/metrics/node_modules/@cubejs-backend/shared/src/promises.ts:139:9)
(node:8461) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 41)
```

**Expected behavior**
To startup without issue

**Screenshots**

**Version:**
`0.27.30`

**Additional context**
Looks like this issue almost: https://github.com/cube-js/cube.js/issues/2431

**Comment by ovr** [comment]
@joshhubers Do you use an official docker image?

Thanks

**Comment by joshhubers** [comment]
Hi @ovr,

This is not using the docker image, I found commenting out the logging configuration on the server core made the error go away. This is the logging config that I have temporarily removed just to get running:

```
  const serverCore = CubejsServerCore.create({
  
    ...

    logger: process.env.NODE_ENV === 'development' ? undefined : (msg, params) => {
      const { error, warning } = params;
      const level = (()=>{
        switch(true) {
          case error:
            return 'error';
            break;
          case warning:
            return 'warning';
            break;
          case [
            'REST API Request',
          ].includes(msg):
            return 'info';
            break;
          default:
            return 'debug';
            break;
        }
      })();
      logger.log(level, { type: REQUEST, message: msg, ...params });
    },
    
    ...
    
  });
```

We are using winston for logging if that makes a difference.

**Comment by joshhubers** [comment]
Thank you!
