### ISSUE TITLE
SparkSQL Connection error

### ISSUE THREAD

**Issue by binodsarkar** [cube-js/cube.js#297]
**SparkSQL Connection error**
Spark sql connection through thrift s not working. Please find the error

`Error while loading DB schema
Error: TApplicationException: Required field 'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, username:anonymous, password:) at Client.OpenSession (/home/administrator/Projects/smsrc/node_modules/jshs2/lib/HiveConnection.js:57:18) at client._reqs.(anonymous function) (/home/administrator/Projects/smsrc/node_modules/thrift/lib/nodejs/lib/thrift/connection.js:151:13) at exports.Client.TCLIServiceClient.recv_OpenSession (/home/administrator/Projects/smsrc/node_modules/jshs2/idl/Thrift_0.9.3_Hive_2.1.1/TCLIService.js:2327:12) at /home/administrator/Projects/smsrc/node_modules/thrift/lib/nodejs/lib/thrift/connection.js:157:41 at /home/administrator/Projects/smsrc/node_modules/thrift/lib/nodejs/lib/thrift/buffered_transport.js:48:5 at frames.filter.map.f (/home/administrator/Projects/smsrc/node_modules/@cubejs-backend/hive-driver/driver/TSaslTransport.js:105:52) at Array.map (<anonymous>) at Socket.<anonymous> (/home/administrator/Projects/smsrc/node_modules/@cubejs-backend/hive-driver/driver/TSaslTransport.js:105:43) at Socket.emit (events.js:198:13) at addChunk (_stream_readable.js:287:12)`

**Comment by tromika** [comment]
> Thrift_0.9.3_Hive_2.1.1

Seems there is a version mismatch with the client and between the thrift server.

**Comment by binodsarkar** [comment]
> > Thrift_0.9.3_Hive_2.1.1
> 
> Seems there is a version mismatch between the client and the thrift server.

In that case how to upgrade cubejs hive version? Because my warehouse version in 2.3.2 or any idea how to use sparksql jdbc driver?

**Comment by tromika** [comment]
by default 2.3.4 bundled see https://github.com/cube-js/cube.js/tree/master/packages/cubejs-hive-driver/idl/Hive_2.3.4. So you have to replace the files with the 2.3.2 version inside your cubejs installation.

**Comment by tromika** [comment]
I guess it doesn't solve your problem but might solve someone's in the future, you can find older hive and thrift idls in https://github.com/imjuni/jshs2/tree/master/idl

**Comment by binodsarkar** [comment]
> by default 2.3.4 bundled see https://github.com/cube-js/cube.js/tree/master/packages/cubejs-hive-driver/idl/Hive_2.3.4. So you have to replace the files with the 2.3.2 version inside your cubejs installation.

Connection error for bug fixing version change?

**Comment by binodsarkar** [comment]
> I guess it doesn't solve your problem but might solve someone's in the future, you can find older hive and thrift idls in https://github.com/imjuni/jshs2/tree/master/idl

Thanks I am checking the same. Will update once resolved

**Comment by paveltiunov** [comment]
@binodsarkar Hey Binod! Hive is very sensitive with these version stuff. You should have correct IDL in place: https://github.com/cube-js/cube.js/tree/master/packages/cubejs-hive-driver#contributing-missing-hive-protocol.

On JDBC side: unfortunately node-maven isn't able to install it due to it doesn't support variables AFAIK.

**Comment by CBox** [comment]
Hey, just to make sure what version of SparkSQL is working with CubeJS?

**Comment by tromika** [comment]
Hi @CBox, we are on 2.3.x and it's working properly. I can't say anything about 2.4.x or 3.x unfortunately but keep in mind for the CubeJs and Spark integration the Hive versions matters.

**Comment by paveltiunov** [comment]
This issue is currently outside of our roadmap and we're looking for contributions here!
