### ISSUE TITLE
v0.28 Missing Required Partition Filter (BigQuery)

### ISSUE THREAD

**Issue by acham1** [cube-js/cube.js#3125]
**Describe the bug**
After upgrading to 0.28 we see queries against a [time-partitioned BigQuery table](https://cloud.google.com/bigquery/docs/querying-partitioned-tables#querying_partitioned_tables_2) fail with the error message:

```
Error: Cannot query over table 'REDACTED' without a filter over column(s) 'usage_start_time' that can be used for partition elimination
```

There have been no code changes on our end, and the query works in `0.27`. Our application provides the required constraint on the timeDimension when it builds the Cube query.

```
 ...
  "timeDimensions": [
    {
      "dimension": "REDACTED.usageStartTime",
      "granularity": "day",
      "dateRange": [
        "2021-06-01",
        "2021-06-30"
      ]
    }
  ],
...
```

The offending BigQuery queries in the log seem to be (maybe?) related to cache building, since they're trying to discover the min and max values for the Cube's timeDimension, but they fail because the query predicates lack the required constraints on the partition column (`usage_start_time`).

```
   E.g.
   
    "select min(DATETIME(`REDACTED`.usage_start_time, 'UTC')) from ..."

    "select max(DATETIME(`REDACTED`.usage_start_time, 'UTC')) from ..."
```

Could it be related to the [partition evaluation changes in 0.28](https://forum.cube.dev/t/v0-28-release-notes/248#server-2)?

> Partition evaluation responsibilities have been moved from the schema compiler to the query orchestrator. This allows all time queries for partitioned rollups and fixes querying issues beyond a rollup’s build range. This is also the first step towards rolling window rollups being supported :tada:

**To Reproduce**
1. Run a Cube query against a time-partitioned BigQuery table, which has the `Require partition filter` setting turned on.
2. Observe the error message: `Error: Cannot query over table 'REDACTED' without a filter over column(s) 'usage_start_time' that can be used for partition elimination`

**Expected behavior**
I expect the query to succeed as it did in `0.27`

**Screenshots**
N/A

**Version:**
0.28.0

**Additional context**
N/A

**Comment by paveltiunov** [comment]
@acham1 Hey Alan! Could you please share your cube.js schema?

**Comment by acham1** [comment]
@paveltiunov yep, the schema's like this:

```
const process = require("process");

cube(`GCPBillingDaily`, {
  title: "Costs, Usage and Credit Totals",
  sql: `SELECT *
    FROM \`ternary-prod.data_${COMPILE_CONTEXT.securityContext.tenantID || process.env.DEFAULT_TENANT_ID}\`.gcp_cost_usage_credit`,

  refreshKey: {
    sql: `SELECT COUNT(*) FROM \`ternary-prod.data_${COMPILE_CONTEXT.securityContext.tenantID ||
      process.env.DEFAULT_TENANT_ID}\`.cost_usage_credit WHERE ${FILTER_PARAMS.GCPBillingDaily.usageStartTime.filter("usage_start_time")}`,
  },

  joins: {
    GCPSKUCategories: {
      relationship: "hasOne",
      sql: `${GCPBillingDaily}.sku_id = ${GCPSKUCategories}.sku_id`,
    },
  },

  preAggregations: {
    spendCategoryProjectDate: {
      type: "rollup",
      dimensionReferences: [GCPSKUCategories.skuCategory, projectId, skuDescription],
      measureReferences: [cost, credits],
      timeDimensionReference: usageStartTime,
      granularity: "day",
      partitionGranularity: `month`,
      refreshKey: {
        every: "4 hour",
        incremental: true,
        updateWindow: "7 day",
      },
    },
  },

  measures: {
    cost: {
      type: "sum",
      sql: `COALESCE(${CUBE}.cost, 0.0)`,
      format: "currency",
    },

    credits: {
      type: "sum",
      sql: `COALESCE(${CUBE}.credit_total, 0.0)`,
      format: "currency",
    },
  },

  dimensions: {
    // Ignore - used only because it is required by Cube for joins
    id: {
      sql: `GENERATE_UUID()`,
      type: "string",
      title: "id",
      primaryKey: true,
      shown: false,
    },

    skuDescription: {
      sql: `${CUBE}.sku_description`,
      type: `string`,
      title: `Sku.description`,
    },

    projectId: {
      sql: `${CUBE}.project_id`,
      type: `string`,
      title: `Project.id`,
    },

    usageStartTime: {
      sql: `${CUBE}.usage_start_time`,
      type: `time`,
    },
  },
});
```

**Comment by acham1** [comment]
The query looks like this:

<details> 

```
Dropping Cache: 200862b8-a3c5-4b41-953c-2def4df48cf4-span-1
{
  "cacheKey": [
    "select min(DATETIME(`g_c_p_billing_daily`.usage_start_time, 'UTC')) from `ternary-prod.data_SyYlNf2WE0nN757SyYoX`.gcp_cost_usage_credit AS `g_c_p_billing_daily`",
    []
  ]
}
Error: Cannot query over table 'ternary-prod.data_SyYlNf2WE0nN757SyYoX.gcp_cost_usage_credit_nvPwM7vS2BJAJkE6L6MM' without a filter over column(s) 'usage_start_time' that can be used for partition elimination
    at QueryQueue.parseResult (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:132:13)
    at QueryQueue.executeInQueue (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:121:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at PreAggregationLoadCache.keyQueryResult (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:301:75)
    at /Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1104:76
    at async Promise.all (index 0)
    at PreAggregationPartitionRangeLoader.partitionRanges (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1102:34)
    at PreAggregationPartitionRangeLoader.loadPreAggregations (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1052:31)
    at QueryOrchestrator.fetchQuery (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:97:47)
    at OrchestratorApi.executeQuery (/Users/alan/Code/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:57:20)
    at /Users/alan/Code/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:797:26
    at async Promise.all (index 0)
    at ApiGateway.load (/Users/alan/Code/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:782:23)
    at /Users/alan/Code/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:281:7
```

</details>

**Comment by acham1** [comment]
The error logs like this:

<details>

```
Dropping Cache: 200862b8-a3c5-4b41-953c-2def4df48cf4-span-1
{
  "cacheKey": [
    "select min(DATETIME(`g_c_p_billing_daily`.usage_start_time, 'UTC')) from `ternary-prod.data_SyYlNf2WE0nN757SyYoX`.gcp_cost_usage_credit AS `g_c_p_billing_daily`",
    []
  ]
}
Error: Cannot query over table 'ternary-prod.data_SyYlNf2WE0nN757SyYoX.gcp_cost_usage_credit_nvPwM7vS2BJAJkE6L6MM' without a filter over column(s) 'usage_start_time' that can be used for partition elimination
    at QueryQueue.parseResult (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:132:13)
    at QueryQueue.executeInQueue (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:121:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at PreAggregationLoadCache.keyQueryResult (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:301:75)
    at /Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1104:76
    at async Promise.all (index 0)
    at PreAggregationPartitionRangeLoader.partitionRanges (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1102:34)
    at PreAggregationPartitionRangeLoader.loadPreAggregations (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1052:31)
    at QueryOrchestrator.fetchQuery (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:97:47)
    at OrchestratorApi.executeQuery (/Users/alan/Code/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:57:20)
    at /Users/alan/Code/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:797:26
    at async Promise.all (index 0)
    at ApiGateway.load (/Users/alan/Code/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:782:23)
    at /Users/alan/Code/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:281:7

...

Error: Cannot query over table 'ternary-prod.data_SyYlNf2WE0nN757SyYoX.gcp_cost_usage_credit_nvPwM7vS2BJAJkE6L6MM' without a filter over column(s) 'usage_start_time' that can be used for partition elimination
Orchestrator error: 200862b8-a3c5-4b41-953c-2def4df48cf4-span-1 (4719ms)

...

{
  "params": [
    "Commitment\\%Year",
    "2021-07-01T00:00:00.000",
    "2021-07-31T23:59:59.999"
  ]
}
Error: Cannot query over table 'ternary-prod.data_SyYlNf2WE0nN757SyYoX.gcp_cost_usage_credit_nvPwM7vS2BJAJkE6L6MM' without a filter over column(s) 'usage_start_time' that can be used for partition elimination
    at QueryQueue.parseResult (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:132:13)
    at QueryQueue.executeInQueue (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:121:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at PreAggregationLoadCache.keyQueryResult (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:301:75)
    at /Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1104:76
    at async Promise.all (index 0)
    at PreAggregationPartitionRangeLoader.partitionRanges (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1102:34)
    at PreAggregationPartitionRangeLoader.loadPreAggregations (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1052:31)
    at QueryOrchestrator.fetchQuery (/Users/alan/Code/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:97:47)
    at OrchestratorApi.executeQuery (/Users/alan/Code/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:57:20)
    at /Users/alan/Code/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:797:26
    at async Promise.all (index 0)
    at ApiGateway.load (/Users/alan/Code/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:782:23)
    at /Users/alan/Code/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:281:7
Error querying db: 200862b8-a3c5-4b41-953c-2def4df48cf4-span-1
```

</details>

**Comment by acham1** [comment]
An example query that triggers the error looks like this:

<details>

```
{
  "measures": [
    "GCPBillingDaily.cost",
    "GCPBillingDaily.credits"
  ],
  "timeDimensions": [
    {
      "dimension": "GCPBillingDaily.usageStartTime",
      "granularity": "day",
      "dateRange": [
        "2021-06-01",
        "2021-06-30"
      ]
    }
  ],
  "order": {
    "GCPBillingDaily.usageStartTime": "asc"
  },
  "dimensions": [],
  "filters": [
    {
      "member": "GCPBillingDaily.skuDescription",
      "operator": "notContains",
      "values": [
        "Commitment%Year"
      ]
    }
  ]
}
```

</details>

**Comment by paveltiunov** [comment]
@acham1 I see. Starting 0.28 `buildRangeStart` and `buildRangeEnd` would be always triggered for partitioned rollups even if you don't use a scheduled refresh. Please set those correctly using https://cube.dev/docs/schema/reference/pre-aggregations#build-range-start-and-build-range-end. @hassankhan we need to document this.

**Comment by acham1** [comment]
Thanks Pavel; I'll give this a try and report back here : )

**Comment by acham1** [comment]
I added explicit definitions for `buildRangeStart` and `buildRangeEnd` as advised; that solves it! Thanks!
