### ISSUE TITLE
CLI create command fails

### ISSUE THREAD

**Issue by tchell** [cube-js/cube.js#3247]
**Describe the bug**
Running the CLI create command fails to create a project:
```
$ cubejs create hello-world -d postgres
- Creating project structure
- Installing server dependencies
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 575 packages in 15.737s
found 0 vulnerabilities

- Installing DB driver dependencies

Cube.js Error ---------------------------------------

Error: @cubejs-backend/server dependency not found. Please run this command from project directory.
    at Object.requireFromPackage (/home/tan/.nvm/versions/node/v14.17.0/lib/node_modules/cubejs-cli/node_modules/@cubejs-backend/shared/src/package.ts:56:11)
    at create (/home/tan/.nvm/versions/node/v14.17.0/lib/node_modules/cubejs-cli/src/command/create.ts:81:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**To Reproduce**
1. install the cli via: `npm install -g cubejs-cli` (I'm assuming this is the intended way? I couldn't spot the intended method in the docs...)
2. run the cli as described in the docs: `cubejs create hello-world -d postgres` OR `npx cubejs-cli create hello-world -d postgres`

**Expected behavior**
Should create a scaffolded project.

**Version:**
cubejs: 0.28.18
node: v14.17.0
'OS': Pop!_OS 21.04

**Comment by paveltiunov** [comment]
Hey @tchell ! Unfortunately, we can't reproduce it. Could you please try again and see if it still persists? If it's still persists can you share the contents of your node_modules in the hello-world directory?

**Comment by tchell** [comment]
I also can't reproduce after trying again. Not sure what happened, I must have had something else going on...
