### ISSUE TITLE
Pre Aggregations on Dev fails with Internal: Execution error: Internal: File not found

### ISSUE THREAD

**Issue by PieterVanZyl-Dev** [cube-js/cube.js#3448]
**Describe the bug**
When I add a pre aggregation to my local cube setup
It throws an error when I query results for that pre aggregation

Internal: Execution error: Internal: File not found: C:\Users\UserName\cube-be\.cubestore\data\449.chunk.parquet

This doesn't happen on Staging where we are running the docker container only with node on all the dev machines

**To Reproduce**
1. Add a new pre aggregation schema to a cube
```
    SisumValueMqCiY: {
      measures: [cube.sumValue],
      dimensions: [cube.featureId, cube.sectorId,],
      timeDimension: cube.date,
      granularity: `year`
    },
  ```
2. On playground or with cube js client make a query that will hit that pre aggregation.
{
  "measures": [
    "cube.sumValue"
  ],
  "timeDimensions": [
    {
      "dimension": "cube.date",
      "granularity": "year"
    }
  ],
  "order": {
    "cube.date": "asc"
  },
  "filters": [
    {
      "member": "cube.sectorId",
      "operator": "equals",
      "values": [
        "2"
      ]
    },
    {
      "member": "cube.featureId",
      "operator": "equals",
      "values": [
        "10",
        "12"
      ]
    }
  ],
}
3. See error

**Expected behavior**
I expect the query to return a result set and not fail.

Or for the query to kick off the pre aggregation query and wait for the files to be created.

**Screenshots**

� Cube Store (0.28.32) is assigned to 3030 port.
� Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
� Dev environment available at http://localhost:4000
� Cube.js server (0.28.32) is listening on 4000

**Additional context**

**Comment by paveltiunov** [comment]
Hey @PieterVanZyl-Dev ! Could you please share `CUBESTORE_LOG_LEVEL=debug` logs? Also are you using distributed file systems or just testing locally?

**Comment by PieterVanZyl-Dev** [comment]
I have sanitized the logs but otherwise it's identical to the errors we are getting 

I am going to try this with a higher refresh key to see if it takes longer before through the internal error.

**Comment by PieterVanZyl-Dev** [comment]
Changing refresh keys made no difference
current work around

Delete the .cubestore file and rerunning the npm run dev

it works for about an hour and then throws these internal errors

**Comment by PieterVanZyl-Dev** [comment]
```
Error querying db: scheduler-cb63d88f-f55f-436e-8b70-7efb6c4c1354 
{}
Error: Query execution timeout after 10 min of waiting
    at QueryQueue.parseResult (C:\Users\user\cube\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryQueue.js:136:13)
    at QueryQueue.executeInQueue (C:\Users\user\cube\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryQueue.js:69:21)
    at PreAggregationLoader.loadPreAggregationWithKeys (C:\Users\user\cube\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\PreAggregations.ts:576:11)
    at PreAggregationLoader.loadPreAggregation (C:\Users\user\cube\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\PreAggregations.ts:484:26)
    at QueryOrchestrator.fetchQuery (C:\Users\user\cube\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryOrchestrator.ts:97:59)
    at OrchestratorApi.executeQuery (C:\Users\user\cube\node_modules\@cubejs-backend\server-core\src\core\OrchestratorApi.ts:57:20)
    at C:\Users\user\cube\node_modules\@cubejs-backend\server-core\src\core\RefreshScheduler.ts:384:13
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at RefreshScheduler.runScheduledRefresh (C:\Users\user\cubes\node_modules\@cubejs-backend\server-core\src\core\RefreshScheduler.ts:142:9)
    at async Promise.all (index 0)
    at Timeout._onTimeout (C:\Users\pivanzyl\Projects\cube-be\node_modules\@cubejs-backend\shared\src\promises.ts:139:9)
Refresh Scheduler Error: scheduler-cb63d88f-f55f-436e-8b70-7efb6c4c1354
{
  "securityContext": {}
}
Error: Query execution timeout after 10 min of waiting

```

Today I also noticed this error which I'm wondering if it's related ?

**Comment by PieterVanZyl-Dev** [comment]
This has gone away after reducing the size of our table, and it was only happening on Windows

**Comment by igorlukanin** [comment]
@paveltiunov It seems like two more users reported the same issue on our Slack recently: https://cube-js.slack.com/archives/CC0403RRR/p1638384980423100

**Comment by HardRock4Life** [comment]
I'm running into the same issue when building a query with a table that also contains 100k rows, just like at @PieterVanZyl-Dev.
First, the query runs fine, but when I refresh the page and try to build the same query once again, the error appears. The workaround with deleting `.cubestore` folder works, but lasts even less that an hour. Is it possible to increase a memory pool or add some function that cleans memory storage?

The logs are:

```
2022-03-21 10:37:33,785 ERROR [cubestore::queryplanner::query_executor] <pid:34948> Error Query (546.3µs):
Limit: 10000
  Projection: #SUM(trees__main.trees__count) AS trees__count
    Aggregate: groupBy=[[]], aggr=[[SUM(#trees__main.trees__count)]]
      ClusterSend
        TableScan: trees__main projection=Some([1])
2022-03-21 10:37:33,787 ERROR [cubestore::queryplanner::query_executor] <pid:34948> Error Query Physical Plan (546.3µs): GlobalLimitExec {
    input: ProjectionExec {
        expr: [
            (
                Column {
                    name: "SUM(trees__main.trees__count)",
                    index: 0,
                },
                "trees__count",
            ),
        ],
        schema: Schema {
            fields: [
                Field {
                    name: "trees__count",
                    data_type: Int64,
                    nullable: true,
                    dict_id: 0,
                    dict_is_ordered: false,
                    metadata: None,
                },
            ],
            metadata: {},
        },
        input: HashAggregateExec {
            strategy: Hash,
            output_sort_order: None,
            mode: Final,
            group_expr: [],
            aggr_expr: [
                Sum {
                    name: "SUM(trees__count)",
                    data_type: Int64,
                    expr: Column {
                        name: "trees__count",
                        index: 0,
                    },
                    nullable: true,
                },
            ],
            input: ClusterSendExec: Schema { fields: [Field { name: "SUM(trees__count)[sum]", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }], metadata: {} }: [("localhost", [(1, RowRange { start: None, end: None }), (2, RowRange { start: None, end: None }), (3, RowRange { start: None, end: None }), (4, RowRange { start: None, end: None })])],
            schema: Schema {
                fields: [
                    Field {
                        name: "SUM(trees__count)",
                        data_type: Int64,
                        nullable: true,
                        dict_id: 0,
                        dict_is_ordered: false,
                        metadata: None,
                    },
                ],
                metadata: {},
            },
            input_schema: Schema {
                fields: [
                    Field {
                        name: "trees__count",
                        data_type: Int64,
                        nullable: true,
                        dict_id: 0,
                        dict_is_ordered: false,
                        metadata: None,
                    },
                ],
                metadata: {},
            },
            output_rows: SQLMetric {
                value: 0,
                metric_type: Counter,
            },
        },
    },
    limit: 10000,
}
2022-03-21 10:37:33,789 ERROR [cubestore::http] <pid:34948> Error processing HTTP command: Internal: Execution error: Internal: File not found: C:\Users\UserName\hello-world_2\.cubestore\data\1-3s2pvavg.chunk.parquet
disabled backtrace
Error while querying: 5566a9f3-80c3-4e5d-a62d-13121598824f-span-1 (16ms)
{
  "queueSize": 0,
  "queryKey": [
    "SELECT sum(`trees__count`) `trees__count` FROM dev_pre_aggregations.trees_main_21jqdgbq_3q3wnrd5_1h3ggvn AS `trees__main`  LIMIT 10000",
    []
  ],
  "queuePrefix": "SQL_QUERY_EXT_STANDALONE",
  "timeInQueue": 0
}
Error: Internal: Execution error: Internal: File not found: C:\Users\UserName\hello-world_2\.cubestore\data\1-3s2pvavg.chunk.parquet
    at WebSocket.<anonymous> (C:\Users\UserName\hello-world_2\node_modules\@cubejs-backend\cubestore-driver\src\WebSocketConnection.ts:87:30)
    at WebSocket.emit (events.js:375:28)
    at Receiver.receiverOnMessage (C:\Users\UserName\hello-world_2\node_modules\ws\lib\websocket.js:983:20)
    at Receiver.emit (events.js:375:28)
    at Receiver.dataMessage (C:\Users\UserName\hello-world_2\node_modules\ws\lib\receiver.js:502:14)
    at Receiver.getData (C:\Users\UserName\hello-world_2\node_modules\ws\lib\receiver.js:435:17)
    at Receiver.startLoop (C:\Users\UserName\hello-world_2\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (C:\Users\UserName\hello-world_2\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (C:\Users\UserName\hello-world_2\node_modules\ws\lib\websocket.js:1077:35)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Error querying db: 5566a9f3-80c3-4e5d-a62d-13121598824f-span-1
--
"SELECT sum(`trees__count`) `trees__count` FROM dev_pre_aggregations.trees_main AS `trees__main` LIMIT 10000"
--
{
  "params": []
}
Error: Internal: Execution error: Internal: File not found: C:\Users\UserName\hello-world_2\.cubestore\data\1-3s2pvavg.chunk.parquet
    at QueryQueue.parseResult (C:\Users\UserName\hello-world_2\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryQueue.js:136:13)
    at QueryQueue.executeInQueue (C:\Users\UserName\hello-world_2\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryQueue.js:56:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at QueryCache.cachedQueryResult (C:\Users\UserName\hello-world_2\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryCache.ts:90:15)
    at QueryOrchestrator.fetchQuery (C:\Users\UserName\hello-world_2\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryOrchestrator.ts:117:20)
    at OrchestratorApi.executeQuery (C:\Users\UserName\hello-world_2\node_modules\@cubejs-backend\server-core\src\core\OrchestratorApi.ts:57:20)
    at C:\Users\UserName\hello-world_2\node_modules\@cubejs-backend\api-gateway\src\gateway.ts:867:26
    at async Promise.all (index 0)
    at ApiGateway.load (C:\Users\UserName\hello-world_2\node_modules\@cubejs-backend\api-gateway\src\gateway.ts:852:23)
    at C:\Users\UserName\hello-world_2\node_modules\@cubejs-backend\api-gateway\src\gateway.ts:284:7
Orchestrator error: 5566a9f3-80c3-4e5d-a62d-13121598824f-span-1 (109ms)
--
{
  "measures": [
    "Trees.count"
  ]
}
--
{}
Error: Internal: Execution error: Internal: File not found: C:\Users\UserName\hello-world_2\.cubestore\data\1-3s2pvavg.chunk.parquet
```

**Comment by PieterVanZyl-Dev** [comment]
@HardRock4Life 
I do have one alternative which does work better
Removing the preaggregations in your dev environment resolves this issue

If you don't want to delete .cubestore constantly I suggest removing pre aggregations on your dev enviroment.

**Comment by HardRock4Life** [comment]
@PieterVanZyl-Dev 
Right, it worked! Thank you!

**Comment by paveltiunov** [comment]
We have added multiple fixes that help with this issue but Cube Store still shouldn't be run for production workloads on Windows machines.
