### ISSUE TITLE
cubejs-elasticsearch-driver not compatible with v7.x

### ISSUE THREAD

**Issue by gabri94** [cube-js/cube.js#3520]
**Describe the bug**
The backend package works with elasticsearch up to v6.8. With v7.x it causes the following error:

```
ResponseError: illegal_argument_exception
    at onBody (/cube/node_modules/@elastic/elasticsearch/lib/Transport.js:337:23)
    at IncomingMessage.onEnd (/cube/node_modules/@elastic/elasticsearch/lib/Transport.js:264:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

 ```

I've tested this behaviour both with elastic.io and a local vanilla elasticsearch v7.15 image.
On the other hand, the library works correctly with elasticsearch v.6.8.18

**To Reproduce**
- Deploy elasticsearch v7.15 using docker.
- Try to connect cube.js by following the instructions on the wiki
- Open the cube.js schema and see the error.

**Expected behavior**
The lib should work with the latest version of elasticsearch

**Comment by stueccles** [comment]
Any chance of getting this merged in? @gabri94 fix seems to work with Elastic Cloud which is running on 7.16

**Comment by paveltiunov** [comment]
@stueccles @gabri94 We just need a PR here.

**Comment by AlbanCrepel** [comment]
Any update on the PR @gabri94 ?

**Comment by gabri94** [comment]
The fix is only partially working, so It doesn't make sense to merge it.

**Comment by nassima-creator** [comment]
issue still persist (trying with ElasticSearch 7.15)

**Comment by shivam145** [comment]
i had made changes as present in @gabri94 's PR and also added a small tweak in one of the line as shown below and it worked for me in version 7.14.1

`const props = mappings.body[index].mappings.properties || {};`

**Comment by tewnut** [comment]
I have similar issue on latest elasticsearch: 8.6.2
