### ISSUE TITLE
npm audit fix breaks cubejs-server

### ISSUE THREAD

**Issue by velimato** [cube-js/cube.js#3754]
Doing npm audit fix breaks cubejs-server. I have tried this on cubejs-server versions 0.28.58 and 0.28.61. Error message when starting cubejs-server

/Users/<name>/Documents/<project-name>/cubejs/node_modules/cli-ux/lib/styled/table.js:314
})(table = exports.table || (exports.table = {}));
 ^
TypeError: Cannot read properties of undefined (reading 'string')
  at /Users/<name>/Documents/<project-name>/cubejs/node_modules/cli-ux/lib/styled/table.js:285:34
  at Object.<anonymous> (/Users/<name>/Documents/<project-name>/cubejs/node_modules/cli-ux/lib/styled/table.js:314:3)
  at Module._compile (node:internal/modules/cjs/loader:1101:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
  at Module.load (node:internal/modules/cjs/loader:981:32)
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  at Module.require (node:internal/modules/cjs/loader:1005:19)
  at require (node:internal/modules/cjs/helpers:102:18)
  at Object.<anonymous> (/Users/<name>/Documents/<project-name>/cubejs/node_modules/cli-ux/lib/index.js:14:36)
  at Module._compile (node:internal/modules/cjs/loader:1101:14)

**Comment by igorlukanin** [comment]
@velimato Thanks for filing this!

**Comment by paveltiunov** [comment]
I guess it'd require an update of `@oclif/dev-cli`.
