### ISSUE TITLE
Installation Error: Cube Store v0.29.18 Artifact for darwin is not found. Most probably it is still building. 

### ISSUE THREAD

**Issue by ranrao** [cube-js/cube.js#3899]
As per documentation, when I execute the `cubejs-cli create` command, running into `@cubejs-backend/native` error. Please share any ideas on how to overcome the issue. Highly appreciate. Thank you. 

```
~w/Cube/ npx cubejs-cli create hello-world -d postgres
npx: installed 209 in 14.302s
- Creating project structure
- Installing server dependencies
npm WARN deprecated @hapi/joi@17.1.1: Switch to 'npm install joi'
npm WARN deprecated @hapi/address@4.1.0: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/formula@2.0.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated @hapi/pinpoint@2.0.0: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> @cubejs-backend/native@0.29.18 install /Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@cubejs-backend/native
> node-pre-gyp install || echo 'Your system is not supported by @cubejs-backend/native, some feature will be unavailable.'

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: ENOENT: no such file or directory, open '/Users/ranjanimanjunath/bundle.pem'
node-pre-gyp ERR! stack     at Object.openSync (fs.js:498:3)
node-pre-gyp ERR! stack     at Object.readFileSync (fs.js:394:35)
node-pre-gyp ERR! stack     at place_binary (/Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@mapbox/node-pre-gyp/lib/install.js:45:27)
node-pre-gyp ERR! stack     at /Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@mapbox/node-pre-gyp/lib/install.js:216:11
node-pre-gyp ERR! System Darwin 19.5.0
node-pre-gyp ERR! command "/Users/ranjanimanjunath/.nvm/versions/node/v14.17.5/bin/node" "/Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@cubejs-backend/native
node-pre-gyp ERR! node -v v14.17.5
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok 
ENOENT: no such file or directory, open '/Users/ranjanimanjunath/bundle.pem'
Your system is not supported by @cubejs-backend/native, some feature will be unavailable.

> @cubejs-backend/cubestore@0.29.18 postinstall /Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@cubejs-backend/cubestore
> node bin/post-install


Cube.js Cube Store Installer ---------------------------------------

Error: Cube Store v0.29.18 Artifact for darwin is not found. Most probably it is still building. Please try again later.
    at Object.downloadBinaryFromRelease (/Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@cubejs-backend/cubestore/js-wrapper/src/download.ts:87:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@cubejs-backend/cubestore/js-wrapper/src/post-install.ts:12:7

Need some help? -------------------------------------

  Ask this question in Cube.js Slack: https://slack.cube.dev
  Post an issue: https://github.com/cube-js/cube.js/issues

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @cubejs-backend/cubestore@0.29.18 postinstall: `node bin/post-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @cubejs-backend/cubestore@0.29.18 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ranjanimanjunath/.npm/_logs/2022-01-10T07_51_52_838Z-debug.log

Cube.js Error ---------------------------------------

Error: npm install --save-dev @cubejs-backend/server failed with exit code 1
    at ChildProcess.<anonymous> (/Users/ranjanimanjunath/.npm/_npx/80897/lib/node_modules/cubejs-cli/src/utils.ts:14:16)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

Need some help? -------------------------------------

  Ask this question in Cube.js Slack: https://slack.cube.dev
  Post an issue: https://github.com/cube-js/cube.js/issues

 ~w/Cube/ 

```

Node version: v14.17.5

**Comment by ranrao** [comment]
Duplicate issue.
