### ISSUE TITLE
run-scheduled-refresh REST endpoint returns error

### ISSUE THREAD

**Issue by cristipp** [cube-js/cube.js#3998]
**Describe the bug**
On a fresh cubejs project, run-scheduled-refresh REST endpoint returns error

**To Reproduce**

```
$ cubejs create pg -d postgres
$ cd pg
$ yarn dev
$ curl \
 -H "Authorization: SECRET" \
 -G --data-urlencode 'query={}' \
http://localhost:4000/cubejs-api/v1/run-scheduled-refresh
{"error":"TypeError: Cannot create proxy with a non-object as target or handler"}
```

**Expected behavior**

```
$ curl \
 -H "Authorization: SECRET" \
 -G --data-urlencode 'query={}' \
http://localhost:4000/cubejs-api/v1/run-scheduled-refresh
{"finished":true}
```

**Version:**

```
$ cubejs-server --version
@cubejs-backend/server/0.29.23 darwin-x64 node-v16.13.1
```

**Comment by cristipp** [comment]
Stack trace:

```
TypeError: Cannot create proxy with a non-object as target or handler
    at PostgresQuery.contextSymbolsProxy (/Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2373:12)
    at /Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2365:27
    at XWrap.f (/Users/cristipp/work/tutorials/pg/node_modules/ramda/src/map.js:78:20)
    at XWrap.@@transducer/step (/Users/cristipp/work/tutorials/pg/node_modules/ramda/src/internal/_xwrap.js:17:17)
    at _arrayReduce (/Users/cristipp/work/tutorials/pg/node_modules/ramda/src/internal/_reduce.js:18:34)
    at _reduce (/Users/cristipp/work/tutorials/pg/node_modules/ramda/src/internal/_reduce.js:60:12)
    at map (/Users/cristipp/work/tutorials/pg/node_modules/ramda/src/map.js:77:14)
    at /Users/cristipp/work/tutorials/pg/node_modules/ramda/src/internal/_dispatchable.js:50:15
    at Object.f2 [as map] (/Users/cristipp/work/tutorials/pg/node_modules/ramda/src/internal/_curry2.js:34:14)
    at PostgresQuery.parametrizedContextSymbols (/Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2364:12)
    at PostgresQuery.evaluateSql (/Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1512:28)
    at PostgresQuery.autoPrefixAndEvaluateSql (/Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1476:55)
    at PostgresQuery.evaluateSymbolSql (/Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1467:21)
    at PostgresQuery.traverseSymbol (/Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1186:35)
    at /Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1224:31
    at PostgresQuery.evaluateSymbolSqlWithContext (/Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1582:22)
    at PostgresQuery.collectCubeNamesFor (/Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1528:10)
    at /Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1224:17
    at CompilerCache.cache (/Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/QueryCache.js:22:28)
    at /Users/cristipp/work/tutorials/pg/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1220:39
    at _map (/Users/cristipp/work/tutorials/pg/node_modules/ramda/src/internal/_map.js:7:19)
    at map (/Users/cristipp/work/tutorials/pg/node_modules/ramda/src/map.js:83:14)
```
