### ISSUE TITLE
Gracefully handle redis connection error

### ISSUE THREAD

**Issue by jcw-** [cube-js/cube.js#432]
**Describe the bug**
During operation, if a redis connection error occurs, the server crashes and needs a restart to recover.

Example Redis Errors:
`ERR max number of clients reached`
`Error: Redis connection to <server> failed - write EPIPE`

This leads to updates to refresh keys failing like this:

```
21 Feb 2020 16:36:10.245536 <190>1 2020-02-21T23:36:09.209422+00:00 host app web.2 - {"message":"Dropping Cache","cacheKey":["SELECT CASE\n WHEN NOW() < $1::timestamptz + interval '12 month' THEN FLOOR(EXTRACT(EPOCH FROM NOW()) / 86400) END",["2019-02-28T23:59:59Z"]],"error":"TypeError: Cannot read property 'queryKey' of null\n at QueryQueue.executeInQueue (/app/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:72:28)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
21 Feb 2020 16:36:10.245536 <190>1 2020-02-21T23:36:09.209650+00:00 host app web.2 - {"message":"Error renewing","cacheKey":["SELECT CASE\n WHEN NOW() < $1::timestamptz + interval '12 month' THEN FLOOR(EXTRACT(EPOCH FROM NOW()) / 86400) END",["2019-02-28T23:59:59Z"]],"error":"TypeError: Cannot read property 'queryKey' of null\n at QueryQueue.executeInQueue (/app/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:72:28)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
21 Feb 2020 16:36:10.245536 <190>1 2020-02-21T23:36:09.220330+00:00 host app web.2 - {"message":"Dropping Cache","cacheKey":["SELECT CASE\n WHEN NOW() < $1::timestamptz + interval '12 month' THEN FLOOR(EXTRACT(EPOCH FROM NOW()) / 86400) END",["2019-02-28T23:59:59Z"]],"error":"TypeError: Cannot read property 'queryKey' of null\n at QueryQueue.executeInQueue (/app/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:72:28)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
21 Feb 2020 16:36:10.245536 <190>1 2020-02-21T23:36:09.220475+00:00 host app web.2 - {"message":"Error renewing","cacheKey":["SELECT CASE\n WHEN NOW() < $1::timestamptz + interval '12 month' THEN FLOOR(EXTRACT(EPOCH FROM NOW()) / 86400) END",["2019-02-28T23:59:59Z"]],"error":"TypeError: Cannot read property 'queryKey' of null\n at QueryQueue.executeInQueue (/app/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:72:28)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
21 Feb 2020 16:36:10.245536 <190>1 2020-02-21T23:36:09.220837+00:00 host app web.2 - {"message":"Dropping Cache","cacheKey":["SELECT CASE\n WHEN NOW() < $1::timestamptz + interval '12 month' THEN FLOOR(EXTRACT(EPOCH FROM NOW()) / 86400) END",["2019-03-31T23:59:59Z"]],"error":"TypeError: Cannot read property 'queryKey' of null\n at QueryQueue.executeInQueue (/app/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:72:28)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
21 Feb 2020 16:36:10.245536 <190>1 2020-02-21T23:36:09.220957+00:00 host app web.2 - {"message":"Error renewing","cacheKey":["SELECT CASE\n WHEN NOW() < $1::timestamptz + interval '12 month' THEN FLOOR(EXTRACT(EPOCH FROM NOW()) / 86400) END",["2019-03-31T23:59:59Z"]],"error":"TypeError: Cannot read property 'queryKey' of null\n at QueryQueue.executeInQueue (/app/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:72:28)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
21 Feb 2020 16:36:10.643500 <190>1 2020-02-21T23:36:09.585807+00:00 host app web.1 - {"message":"Dropping Cache","cacheKey":["SELECT CASE\n WHEN NOW() < $1::timestamptz + interval '12 month' THEN FLOOR(EXTRACT(EPOCH FROM NOW()) / 86400) END",["2019-08-31T23:59:59Z"]],"error":"TypeError: Cannot read property 'queryKey' of null\n at QueryQueue.executeInQueue (/app/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:72:28)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
21 Feb 2020 16:36:10.643500 <190>1 2020-02-21T23:36:09.586068+00:00 host app web.1 - {"message":"Error renewing","cacheKey":["SELECT CASE\n WHEN NOW() < $1::timestamptz + interval '12 month' THEN FLOOR(EXTRACT(EPOCH FROM NOW()) / 86400) END",["2019-08-31T23:59:59Z"]],"error":"TypeError: Cannot read property 'queryKey' of null\n at QueryQueue.executeInQueue (/app/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:72:28)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
21 Feb 2020 16:36:10.643500 <190>1 2020-02-21T23:36:09.593549+00:00 host app web.1 - {"message":"Dropping Cache","cacheKey":["SELECT CASE\n WHEN NOW() < $1::timestamptz + interval '12 month' THEN FLOOR(EXTRACT(EPOCH FROM NOW()) / 86400) END",["2019-10-31T23:59:59Z"]],"error":"TypeError: Cannot read property 'queryKey' of null\n at QueryQueue.executeInQueue (/app/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:72:28)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
21 Feb 2020 16:36:10.643500 <190>1 2020-02-21T23:36:09.593699+00:00 host app web.1 - {"message":"Error renewing","cacheKey":["SELECT CASE\n WHEN NOW() < $1::timestamptz + interval '12 month' THEN FLOOR(EXTRACT(EPOCH FROM NOW()) / 86400) END",["2019-10-31T23:59:59Z"]],"error":"TypeError: Cannot read property 'queryKey' of null\n at QueryQueue.executeInQueue (/app/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:72:28)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
```

**To Reproduce**
1. Run a load test (e.g. flood.io) against a server with limited client connections (e.g. 5)
1. Observe that every five minutes, there is a spike in refresh key cache invalidation
1. During this spike, the max clients to redis can be hit, resulting in an error from the redis library
1. This results in the node instance crashing

**Expected behavior**
1. Graceful recovery (E.g. retry connection with incremental backoff)

**Version:**
0.17.10

**Comment by paveltiunov** [comment]
@jcw- Hey Jc! Thanks for posting this! This one is indeed tough one. We have same issue already here #104 . I'd rather go with connection pool/limiter because in case of burst local waiting is faster than retrying connections with exponential backoff.

**Comment by paveltiunov** [comment]
Let's continue conversation in #104
