### ISSUE TITLE
can't install cubejs with sqlite

### ISSUE THREAD

**Issue by mr-m0nst3r** [cube-js/cube.js#4414]
I'm new to cubejs, but attracted by the idea.

I have a sqlite database which is from one of my projects, but I'm just following the tutorial by issuing the following command:
```
npx cubejs-cli create cube-test -d sqlite
```

and got the following error:
```
added 646 packages in 27s
- Installing DB driver dependencies
npm ERR! code 1
npm ERR! path /Users/m0nst3r/dev/py/tespla/cube-test/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.9 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/m0nst3r/dev/py/tespla/cube-test/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/m0nst3r/dev/py/tespla/cube-test/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/m0nst3r/dev/py/tespla/cube-test/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/m0nst3r/Library/Caches/node-gyp/16.13.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/m0nst3r/Library/Caches/node-gyp/16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/m0nst3r/dev/py/tespla/cube-test/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/m0nst3r/Library/Caches/node-gyp/16.13.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/m0nst3r/dev/py/tespla/cube-test/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/m0nst3r/dev/py/tespla/cube-test/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/Users/m0nst3r/.nvm/versions/node/v16.13.1/bin/node" "/Users/m0nst3r/dev/py/tespla/cube-test/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/m0nst3r/dev/py/tespla/cube-test/node_modules/sqlite3
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m0nst3r/.npm/_logs/2022-04-20T03_59_18_906Z-debug.log

Cube.js Error ---------------------------------------

Error: npm install --save-dev @cubejs-backend/sqlite-driver failed with exit code 1
    at ChildProcess.<anonymous> (/Users/m0nst3r/.npm/_npx/b15e41626979eec6/node_modules/cubejs-cli/src/utils.ts:14:16)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

Need some help? -------------------------------------

  Ask this question in Cube.js Slack: https://slack.cube.dev
  Post an issue: https://github.com/cube-js/cube.js/issues

```

*
**Version:**
Don't know, because haven't got into the process of installing cubejs.

**Additional context**
apple silicon m1 mac.

**Comment by mr-m0nst3r** [comment]
it's sqlite driver issue. closed
