### ISSUE TITLE
AthenaDriver returns an error when data result is empty

### ISSUE THREAD

**Issue by bong-sc** [cube-js/cube.js#4418]
**Describe the bug**

When we use `AthenaDriver` to build pre-aggregation data and one of the partitions has an empty data set, `AthenaDriver` will return an error:
```
Error: Unable to UNLOAD table s3://s3_bucket/output/dev_pre_aggregations.inspection_rollup_main20211101_zl0fqgnd_kxlzdp3z_1h61ct3
    at AthenaDriver.unload (/cube/node_modules/@cubejs-backend/athena-driver/src/AthenaDriver.ts:147:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at PreAggregationLoader.downloadTempExternalPreAggregation (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:923:21)
    at PreAggregationLoader.refreshImplTempTableExternalStrategy (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:814:25)
    at Object.query (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:280:26)
    at QueryQueue.processQuery (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:432:21)
Error querying db: scheduler-871ade1f-a7f8-49f4-a052-23f311dd3e03-span-1 
```

Instead, `AthenaDriver` should skip unloading data if the data set is empty. The issue doesn't happen with `Redshift` as it's covered here https://github.com/cube-js/cube.js/blob/master/packages/cubejs-redshift-driver/src/RedshiftDriver.ts#L132. I suppose we could do a similar thing with `AthenaDriver`.

**To Reproduce**
1. Use Athena as the data source
2. Enable pre-aggregation and one of the partition has empty data set
3. Trigger the refresh worker and notice that there is an error when building pre-aggregations

**Expected behavior**
There should be no error when building pre-aggregations

**Screenshots**

**Minimally reproducible Cube Schema**
N/A

**Version:**
0.29.28

**Additional context**
- Redshift seems to avoid it by checking `unloadTotalRows` in https://github.com/cube-js/cube.js/blob/master/packages/cubejs-redshift-driver/src/RedshiftDriver.ts#L132

**Comment by bong-sc** [comment]
I no longer see the error in v0.30.8.
