### ISSUE TITLE
Cube store exited on startup

### ISSUE THREAD

**Issue by plazasnico** [cube-js/cube.js#4732]
**Describe the bug**
I try to use cubejs with an express app, but when I try to run my app I have an error to start the cube store. I thought that could be a problem with my firewall, so I add the rule to port 0.0.0.0:3030 but that didn't work.

Error querying db: scheduler-516efeae-0d74-41e6-8a33-bb8ea1a43e03 
{} 
Error: Cube Store exited with 1 on startup.
    at QueryQueue.parseResult (/home/pruebas.iatechsolutions.com.co/public/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:138:13)
    at QueryQueue.executeInQueue (/home/pruebas.iatechsolutions.com.co/public/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:57:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at OrchestratorApi.executeQuery (/home/pruebas.iatechsolutions.com.co/public/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:64:20)
    at /home/pruebas.iatechsolutions.com.co/public/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:239:9
    at async Promise.all (index 0)
    at /home/pruebas.iatechsolutions.com.co/public/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:224:7
    at async Promise.all (index 3)
    at RefreshScheduler.refreshCubesRefreshKey (/home/pruebas.iatechsolutions.com.co/public/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:217:5)
    at async Promise.all (index 0)
    at RefreshScheduler.runScheduledRefresh (/home/pruebas.iatechsolutions.com.co/public/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:165:9)
    at async Promise.all (index 0)
    at Timeout._onTimeout (/home/pruebas.iatechsolutions.com.co/public/node_modules/@cubejs-backend/shared/src/promises.ts:139:9)
Refresh Scheduler Error: scheduler-516efeae-0d74-41e6-8a33-bb8ea1a43e03 
{
  "securityContext": {}
} 
Error: Cube Store exited with 1 on startup.

**To Reproduce**
These are my environment variables to setup my cube store

CUBEJS_EXTERNAL_DEFAULT=true
CUBEJS_CACHE_AND_QUEUE_DRIVER=memory

**Screenshots**
![image](https://user-images.githubusercontent.com/81947183/172537195-9a496c01-2358-4830-b972-968f95269245.png)

**Version:**
"@cubejs-backend/cubestore-driver": "^0.30.8",
"@cubejs-backend/mysql-driver": "^0.30.1",
"@cubejs-backend/server-core": "^0.30.10",

**Comment by ovr** [comment]
Hello @plazasnico ,

Can you stop Cube.js, and try to run:

```sh
./node_modules/@cubejs-backend/cubestore/bin/cubestore-dev
```

Do you see any errors in the output?

Thanks

**Comment by plazasnico** [comment]
I ran it and notice that the problem is my OS (CentOs7), since it hasn't the version `GLIBCXX_3.4.21′ and it is only built-in from CentOS 8, so I try to resolve this updating the lib.

`/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found`

I will notify you when I achieve it.

Thanks
