### ISSUE TITLE
Creation of index for PostgreSQL rollup pre-aggregation fails

### ISSUE THREAD

**Issue by kaja78** [cube-js/cube.js#4841]
**Describe the bug**
Indexes in PostgreSQL rollup pre-aggregation fail to build. Invalid non-existing table name is generated into CREATE INDEX SQL statement. Same problem exists for external and internal pre-aggregations. Looks like the content and structure version is doubled in target table name.
If no sqlAlias for rollup pre-aggregation is specified, it is working as expected.

Sample CubeJS error: `Error: relation "dev_pre_aggregations.table_schema_agg_t14s2x2i_mimngfsg_1hbttgk_t14s2x2i_mimngfsg_1h" does not exist`

Sample PostgreSQL error:
```
2022-07-01 13:26:44.330 GMT [142] ERROR:  relation "dev_pre_aggregations.table_schema_agg_t14s2x2i_mimngfsg_1hbttgk_t14s2x2i_mimngfsg_1h" does not exist

2022-07-01 13:26:44.330 GMT [142] STATEMENT:  CREATE INDEX table_schema_agg_t14s2x2i_mimngfsg_1hbttgk ON dev_pre_aggregations.table_schema_agg_t14s2x2i_mimngfsg_1hbttgk_t14s2x2i_mimngfsg_1hbttgk ("table__schema")
```

**To Reproduce**
1. Define index on rollup pre-agg stored in PostgreSQL. Configure scheduled refresh.
2. Start CubeJS refresh worker
3. Check error message in log

**Expected behavior**
No error - rollup pre-aggregation with index is created.

**Screenshots**

**Minimally reproducible Cube Schema**

```javascript
cube(`Table`, {
  sql: `
      select table_schema,table_name from information_schema.tables
    `,

  dimensions: {

    schema: {
      sql: `table_schema`,
      type: `string`
    },

    table: {
      sql: `table_name`,
      type: `string`
    }
  },

  preAggregations: {
    schemaAgg: {
      sqlAlias: `schema_agg`,
      dimensions: [
        CUBE.schema
      ],
      scheduledRefresh: true,
      external: false,
      indexes: {
        schemaIndex: {
          columns: [CUBE.schema],
        }
      }
    },

  },
  dataSource: `default`
});
```

**Version:**
0.30.29

**Full log**:
```
Error while querying: scheduler-9088a1c5-51e6-4039-ac47-9b3fd444f6db (31ms)
{
  "processingId": 1,
  "queueSize": 1,
  "queryKey": [
    [
      "CREATE TABLE dev_pre_aggregations.table_schema_agg AS SELECT\n      \"table\".table_schema \"table__schema\"\n    FROM\n      (\n      select table_schema,table_name from information_schema.tables\n    ) AS \"table\"  GROUP BY 1",
      []
    ],
    [
      {
        "indexName": "table_schema_agg",
        "sql": [
          "CREATE INDEX table_schema_agg ON dev_pre_aggregations.table_schema_agg (\"table__schema\")",
          []
        ]
      }
    ],
    [
      [
        {
          "refresh_key": 460189
        }
      ]
    ]
  ],
  "queuePrefix": "SQL_PRE_AGGREGATIONS_STANDALONE_default",
  "timeInQueue": 2,
  "preAggregationId": "Table.schemaAgg",
  "newVersionEntry": {
    "table_name": "dev_pre_aggregations.table_schema_agg",
    "structure_version": "mimngfsg",
    "content_version": "t14s2x2i",
    "last_updated_at": 1656682004299,
    "naming_version": 2
  },
  "preAggregation": {
    "preAggregationId": "Table.schemaAgg",
    "timezone": "UTC",
    "timestampFormat": "YYYY-MM-DD[T]HH:mm:ss.SSS[Z]",
    "tableName": "dev_pre_aggregations.table_schema_agg",
    "invalidateKeyQueries": [
      [
        "SELECT FLOOR((EXTRACT(EPOCH FROM NOW())) / 3600) as refresh_key",
        [],
        {
          "external": true,
          "renewalThreshold": 10
        }
      ]
    ],
    "type": "rollup",
    "external": false,
    "previewSql": [
      "SELECT * FROM dev_pre_aggregations.table_schema_agg LIMIT 1000",
      []
    ],
    "preAggregationsSchema": "dev_pre_aggregations",
    "loadSql": [
      "CREATE TABLE dev_pre_aggregations.table_schema_agg AS SELECT\n      \"table\".table_schema \"table__schema\"\n    FROM\n      (\n      select table_schema,table_name from information_schema.tables\n    ) AS \"table\"  GROUP BY 1",
      []
    ],
    "sql": [
      "SELECT\n      \"table\".table_schema \"table__schema\"\n    FROM\n      (\n      select table_schema,table_name from information_schema.tables\n    ) AS \"table\"  GROUP BY 1",
      []
    ],
    "uniqueKeyColumns": [
      "\"table__schema\""
    ],
    "dataSource": "default",
    "indexesSql": [
      {
        "indexName": "table_schema_agg",
        "sql": [
          "CREATE INDEX table_schema_agg ON dev_pre_aggregations.table_schema_agg (\"table__schema\")",
          []
        ]
      }
    ],
    "readOnly": false,
    "expandedPartition": true,
    "priority": -1
  },
  "addedToQueueTime": 1656682004300
} 
error: relation "dev_pre_aggregations.table_schema_agg_t14s2x2i_mimngfsg_1hbttgk_t14s2x2i_mimngfsg_1h" does not exist
    at Parser.parseErrorMessage (/Users/karel/IdeaProjects/insights-cubejs-api/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/karel/IdeaProjects/insights-cubejs-api/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/karel/IdeaProjects/insights-cubejs-api/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/karel/IdeaProjects/insights-cubejs-api/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Error querying db: scheduler-9088a1c5-51e6-4039-ac47-9b3fd444f6db 
{} 
Error: relation "dev_pre_aggregations.table_schema_agg_t14s2x2i_mimngfsg_1hbttgk_t14s2x2i_mimngfsg_1h" does not exist
    at QueryQueue.parseResult (/Users/karel/IdeaProjects/insights-cubejs-api/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:138:13)
    at QueryQueue.executeInQueue (/Users/karel/IdeaProjects/insights-cubejs-api/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:127:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PreAggregationLoader.loadPreAggregationWithKeys (/Users/karel/IdeaProjects/insights-cubejs-api/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:631:7)
    at PreAggregationLoader.loadPreAggregation (/Users/karel/IdeaProjects/insights-cubejs-api/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:510:22)
    at QueryOrchestrator.fetchQuery (/Users/karel/IdeaProjects/insights-cubejs-api/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:104:59)
    at OrchestratorApi.executeQuery (/Users/karel/IdeaProjects/insights-cubejs-api/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:64:20)
    at /Users/karel/IdeaProjects/insights-cubejs-api/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:479:13
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at RefreshScheduler.runScheduledRefresh (/Users/karel/IdeaProjects/insights-cubejs-api/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:165:9)
    at async Promise.all (index 0)
    at Timeout._onTimeout (/Users/karel/IdeaProjects/insights-cubejs-api/node_modules/@cubejs-backend/shared/src/promises.ts:139:9)
Refresh Scheduler Error: scheduler-9088a1c5-51e6-4039-ac47-9b3fd444f6db 
{
  "securityContext": {}
} 
Error: relation "dev_pre_aggregations.table_schema_agg_t14s2x2i_mimngfsg_1hbttgk_t14s2x2i_mimngfsg_1h" does not exist

```

**Comment by paveltiunov** [comment]
@kaja78 Storing pre-aggregations in Postgres isn't supported anymore. Please consider using Cube Store.
