### ISSUE TITLE
Error when using rollup pre aggregations

### ISSUE THREAD

**Issue by agnesesim** [cube-js/cube.js#4878]
Premises: I'm using cube js legacy version running on node js and in dev mode (i'm using only the playground localhost). The power shell that is running cube is started in admin mode. The DB linked to cube is MSSQL and the user used to query the database has db_owner role. 

When I try to build a pre-aggregation I get this error:

`Error: Internal: File 4-7ixtwe0p.chunk.parquet can't be listed after upload
    at QueryQueue.parseResult (...\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryQueue.js:138:13)
    at QueryQueue.executeInQueue (...\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryQueue.js:127:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PreAggregationLoader.loadPreAggregationWithKeys (...\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\PreAggregations.ts:631:7)
    at PreAggregationLoader.loadPreAggregation (..\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\PreAggregations.ts:510:22)
    at QueryOrchestrator.fetchQuery (...\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryOrchestrator.ts:104:59)
    at OrchestratorApi.executeQuery (...\node_modules\@cubejs-backend\server-core\src\core\OrchestratorApi.ts:64:20)
    at ...\node_modules\@cubejs-backend\server-core\src\core\RefreshScheduler.ts:479:13
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at RefreshScheduler.runScheduledRefresh (...\node_modules\@cubejs-backend\server-core\src\core\RefreshScheduler.ts:165:9)
    at async Promise.all (index 0)
    at Timeout._onTimeout (...\node_modules\@cubejs-backend\shared\src\promises.ts:139:9)
Refresh Scheduler Error: scheduler-b3286486-3410-463d-ac64-57e5507d8600`

The odd thing is that in the database i see the expected aggregated tables but when it comes to these parquet files i get this error so i think is a problem of cubestore.
If I set in the ENV file **external: false** the preaggregation works fine but cube itself is suggesting me to use these external rollups.

I'm using the 0.30.25 version of cubejs

Thank you in advance for your time

**Comment by paveltiunov** [comment]
@agnesesim Your cluster is most likely misconfigured. Please check your Cube Store storage configuration: https://cube.dev/docs/deployment/overview#cube-store-storage.

**Comment by agnesesim** [comment]
Thank you for your answer!
I tried to set both CUBESTORE_DATA_DIR and CUBESTORE_REMOTE_DIR (in the .env file) but it seems like the program ignore them and keep using the default meta store directory. 
I saw in the docs that cube store is intended to work especially with external buckets like AWS or Google, but i noticed also that there is a possibility to use a local directory (as a "remote directory") instead, even if it's not working for me.

![image](https://user-images.githubusercontent.com/38429734/178241311-8d72c547-1f66-419d-8419-2a7a1aaefa03.png)

As I stated before, even with all these .env edits the program still gives me errors about files that cannot be listed.

**Comment by paveltiunov** [comment]
@agnesesim It's exactly the type of error you'd see if underlying storage doesn't provide the required consistency guarantees. Please consider using distributed FS instead.
