### ISSUE TITLE
Documentation for Deployment are outdated for both Kubernetes and Docker

### ISSUE THREAD

**Issue by johanjvrens** [cube-js/cube.js#5262]
First off, thank you for your awesome work done on this amazing product!

I struggle to follow the documentation for deployment as they are outdated for both kubernetes and docker. The examples that I could access like [kubernetes/cluster](https://github.com/cube-js/cube.js/tree/master/examples/kubernetes/cluster) are 11 months old and contain Enviroment variables that are either depricated or not applicable for newer S3 EXPORT config. Almost all examples in the repo and documentation still use CUBESTORE_REMOTE_DIR although this looks to be incorrect when looking at github issues and env docs that sates: Not required if using GCS/S3. Not recommended for production usage.

**There is a difference between env values generated with the newest cube-cli and the [documentation](https://cube.dev/docs/deployment/overview)**

Which configuration is the correct or preferred config, the documentation or cube-cli?

The following variables isn't even listed on [docs](https://cube.dev/docs/reference/environment-variables), but
is set when project structure is generated with cli :
```text
CUBEJS_EXTERNAL_DEFAULT=true
CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
```
This discrepancies between ENV docs, Deployment Docs, old github repos and cli generated config seems to lead to confusion when I look at the issues logged related to this.

What should a basic setup look like when I want to make use of S3 cloud storage with CUBEJS_DB_EXPORT_BUCKET_TYPE=S3

Kind Regards
Johan

**Comment by narioinc** [comment]
Adding to the dicussion

I have started creating my own version of a Helm chart that i wish to maintain on Github for those looking to use Cubejs on kubernetes.

However, there is a small issue i am running into on the Cubestore-router. FOr some reason it seems to want to parse the env var "CUBESTORE_WORKER_PORT" even though that shouldnt be the case as the router shouldnt parse ENV VARS specific to Cubestore workers

Here is the Kubernetes Env vars for the cubestore router: 
- env:
          - name: CUBESTORE_WORKERS
            value: 'cubestore-worker:10001'
          - name: CUBESTORE_REMOTE_DIR
            value: /cube/data
          - name: CUBESTORE_META_PORT
            value: '9999'
          - name: CUBESTORE_SERVER_NAME
            value: 'cubestore-router:9999' 

Here is the error seen in the cubestore router pod:

2023-06-26 09:31:08,298 INFO  [cubestored] <pid:1> Cube Store version 0.33.29
thread 'main' panicked at 'could not parse environment variable 'CUBESTORE_WORKER_PORT' with 'tcp://10.103.86.46:10001' value: invalid digit found in string', cubestore/src/config/mod.rs:947:19
stack backtrace:
   0: rust_begin_unwind
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/core/src/panicking.rs:142:14
   2: cubestore::config::env_optparse
   3: cubestore::config::Config::default
   4: cubestored::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


Any thing obvious peering out with my setup ? The repo can be foudn here: https://github.com/narioinc/cubejs-helm. the main branch is not in a working condition as PVs are missing. But atleast I would like to see the above error go away. 

@johanjvrens @paveltiunov

**Comment by narioinc** [comment]
@johanjvrens  @paveltiunov 
I have been able to make a more uptodate helm chart to deploy cubejs to kubernetes by following the latest deployment overview documentation
Please find the same here:
https://github.com/narioinc/cubejs-helm

This should deploy the high availability and high throughput setup here: https://cube.dev/docs/deployment/overview

@paveltiunov  would it be useful if I can convert this to a CubejS Kubernetes operator that automates the entire Cubejs setup on top of kubernetes using kubernetes-native entities (statefulsets, configmaps, storege, persistent volumes). 

This will allow organizations to manage their cube core setup in a completely hands free way on top of K8S. Let me know your thoughts.

**Comment by paveltiunov** [comment]
@narioinc Can you make your repo public?

**Comment by narioinc** [comment]
Hi @paveltiunov 

Sure can do. Let me clean up the chart and publish the same. I had to refractor the way the environment variable were loaded in the various deployments in the chart. Will do that today or tomorrow and share the public repo link here for your review. 

There was also a confusion on whether the cube store components (namely the router and the workers) should be deployment or statefulsets. For now I have kept them as stateful sets with a headless service that allows accessing the individual worker components. 

I'll also add a detailed readme so that it is useful for others to check out. 

In the immediate future, I am going to start work on a open source cubejs kubernetes operator that can help everyone run cubejs at scale in kubernetes in a simpler fashion. 

Do let me know your thoughts on the same and if the community can benefit from an kubernetes operator.

**Comment by narioinc** [comment]
@paveltiunov 
The cube-helm repo has been updated with several changes following some basic best practices with regards to helm:
https://github.com/narioinc/cube-helm/

The Values.yaml has been documented to ensure users know which sections to update for their DBs. However, the one component configuration that is still an issue with Helm is configuring the CUBESTORE_WORKERS env in the cube store router and worker.

The issue is that since the specific env var (CUBESTORE_WORKERS) requires a comma separated value of cubestore worker nodes i was not able to add this dynamically during helm creation if the user gives more than 1 replica for their worker nodes. For now, the users need to manually go and update this env var every time they update the number of replicas for their worker nodes.

**Comment by narioinc** [comment]
@paveltiunov  the issue with the CUBESTORE_WORKERS being hard coded got fixed. I was going about in the wrong direction and was able to use Helm flow control variables to achieve the same. Now, the env var in question should get the list of workers dynamically based on the worker replica

**Comment by narioinc** [comment]
@johanjvrens I know this might be too delayed for your needs, but if you are still looking at a "cluster mode" cube deployment then you could give my helm chart a go. thanks
