### ISSUE TITLE
using snowflake driver: after adding refreshKey 1 hour getting error - "Unknown function NOW"

### ISSUE THREAD

**Issue by grinfeld** [cube-js/cube.js#537]
I am using snowflake driver. After adding 
```
 refreshKey: {
    every: `1 hour`
  }
```
for one of my cubes, started to get 

```
{
  "cacheKey": [
    "SELECT FLOOR(EXTRACT(EPOCH FROM NOW()) / 3600)",
    []
  ],
  "requestId": "7ff37d72-8e81-43e4-ad07-f3b64681daa9-span-1"
}
Error: SQL compilation error:
Unknown function NOW
    at QueryQueue.parseResult (/usr/src/app/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:97:13)
    at QueryQueue.executeInQueue (/usr/src/app/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:86:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
using ver. 0.18.6

snowflake doesn't have ``NOW()`` function, but ``CURRENT_DATE `` and ``CURRENT_TIMESTAMP`` instead

**Comment by paveltiunov** [comment]
@grinfeld Hey Mikhail! Thanks for posting this one! Yep. It's lack of implementation for `every`.
