### ISSUE TITLE
Cannot find module 'thrift'

### ISSUE THREAD

**Issue by wcc914** [cube-js/cube.js#541]
I got error when calling `sudo cubejs create hello-world -d hive`. Did i needed to install ather application be run the script?

error message as below:

Error: Cannot find module 'thrift'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/cube/hello-world2/node_modules/@cubejs-backend/hive-driver/driver/TSaslTransport.js:1:78)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by paveltiunov** [comment]
Hey @wcc914! Thanks for heads up! Should be fixed right now.
