### ISSUE TITLE
Error setting up Hive cube

### ISSUE THREAD

**Issue by edreqm** [cube-js/cube.js#544]
I have installed cube.js successfully on Ubuntu 18.04.
When I try to create a Hive project with
`cubejs create test_hive -d hive`
The following error is show:

```
Cube.js Error ---------------------------------------

Error: Cannot find module 'thrift'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/root/test_hive/node_modules/@cubejs-backend/hive-driver/driver/TSaslTransport.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
```

Here is the complete process output:
```
- Creating project structure
- Installing server dependencies
npm notice created a lockfile as package-lock.json. You should commit this file.
+ @cubejs-backend/server@0.18.17
added 296 packages from 231 contributors and audited 4166 packages in 16.357s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

- Installing DB driver dependencies
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

> ws@0.4.32 install /root/test_hive/node_modules/jshs2/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

+ @cubejs-backend/hive-driver@0.18.17
added 37 packages from 43 contributors and audited 4219 packages in 5.233s

11 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (2 low, 1 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
- Writing files from template

Cube.js Error ---------------------------------------

Error: Cannot find module 'thrift'
Require stack:
- /root/test_hive/node_modules/@cubejs-backend/hive-driver/driver/TSaslTransport.js
- /root/test_hive/node_modules/@cubejs-backend/hive-driver/driver/HiveDriver.js
- /usr/local/lib/node_modules/cubejs-cli/utils.js
- /usr/local/lib/node_modules/cubejs-cli/token.js
- /usr/local/lib/node_modules/cubejs-cli/cubejsCli.js
- /usr/local/lib/node_modules/cubejs-cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/root/test_hive/node_modules/@cubejs-backend/hive-driver/driver/TSaslTransport.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)

Need some help? -------------------------------------

  Ask this question in Cube.js Slack: https://slack.cube.dev
  Post an issue: https://github.com/cube-js/cube.js/issues

```

**To Reproduce**
On Ubuntu 18.04:

1. Log as root user

2. Install cubejs

```
apt-get -y install nodejs npm
apt-get -y update -o APT::Sandbox::User=root  \
     && apt-get -y install nodejs npm curl unzip git
npm install -g cubejs-cli
npm install -g n
n --insecure latest
npm set strict-ssl false
```

3. Creta the project
`cubejs create test_hive -d hive`

3. The error message is shown.

**Version:**
Cubejs 0.18.4
Npm 6.7.0
Node 13.12.0

**Comment by paveltiunov** [comment]
@edreqm Hey Edré! Thanks for posting this one! Should be fixed now.
