### ISSUE TITLE
Bigquery Connection Service Account - Unexpected token '<', "<html> <h"... is not valid JSON

### ISSUE THREAD

**Issue by carlonuccio** [cube-js/cube.js#5547]
**Describe the bug**
```
Runtime Error
Cube.js was unable to connect to the specified database.

The database returned the following error:


>Database Error

SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON


Check your database credentials and try again. For more information, visit:

https://cube.dev/docs/config/databases
```

**To Reproduce**
1. Go to Connection
2. Click on Bigquery
3. Upload Service Account

**Expected behavior**
Get Datasets from BQ

**Version:**
Tested on 0.28.43, 0.31.8, 0.31.7.
Works only on 0.26.95

**Additional context**
Deploy on ECS Fargate.

Only 1 Task with:
1 container for API Instance
1 container for Refresh Worker
1 container for Cubestore Router
1 container for Cubestore Worker

**Comment by paveltiunov** [comment]
@carlonuccio Could you please try to reproduce it in [Cube Cloud](https://cube.dev/cloud)? It's too little information to tell anything here.

**Comment by carlonuccio** [comment]
on Cube Cloud, it works.

Additional Context:

for Cube API Instance, I'm specifying the following variables:

```
    CUBEJS_DB_TYPE: "bigquery",
    CUBEJS_DB_BQ_PROJECT_ID: var.bq_project,
    CUBEJS_DB_BQ_CREDENTIALS: filebase64(var.bq_json_service_account),
    CUBEJS_CUBESTORE_HOST: "localhost",
    CUBEJS_REDIS_URL: "redis://${local.redis_address}:6379",
    CUBEJS_API_SECRET: "${local.creds.api_key}",
    CUBEJS_DEV_MODE: true,
    CUBEJS_PG_SQL_PORT: "5432"
```
In this way, it doesn't work.



If I don't specify CUBEJS_DB_TYPE, CUBEJS_DB_BQ_PROJECT_ID, CUBEJS_DB_BQ_CREDENTIALS, the initial page is the connection page. So click on BigQuery connection and try to install @cubejs-backend/bigquery-driver.
This is the log:


```
2022-11-02 10:03:10found 37 vulnerabilities (8 low, 7 moderate, 21 high, 1 critical)
2022-11-02 10:03:10run `npm audit fix` to fix them, or `npm audit` for details
2022-11-02 10:03:10100 packages are looking for funding
2022-11-02 10:03:10run `npm fund` for details
2022-11-02 10:03:09+ @cubejs-backend/bigquery-driver@0.31.9
2022-11-02 10:03:09added 177 packages from 87 contributors, removed 79 packages, updated 1205 packages and audited 1415 packages in 163.912s
2022-11-02 10:03:09npm WARN optional SKIPPING OPTIONAL DEPENDENCY: java@0.12.2 (node_modules/java):
2022-11-02 10:03:09npm WARN optional SKIPPING OPTIONAL DEPENDENCY: java@0.12.2 install: `node-gyp rebuild`
2022-11-02 10:03:09npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
2022-11-02 10:03:09npm WARN @aws-sdk/middleware-sdk-s3@3.41.0 requires a peer of @aws-sdk/signature-v4-crt@^3.31.0 but none is installed. You must install peer dependencies yourself.
2022-11-02 10:03:09npm WARN @aws-sdk/middleware-sdk-s3@3.49.0 requires a peer of @aws-sdk/signature-v4-crt@^3.31.0 but none is installed. You must install peer dependencies yourself.
2022-11-02 10:03:09npm WARN @aws-sdk/middleware-sdk-s3@3.49.0 requires a peer of @aws-sdk/signature-v4-crt@^3.31.0 but none is installed. You must install peer dependencies yourself.
2022-11-02 10:03:09npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
2022-11-02 10:03:09npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2022-11-02 10:03:09npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
2022-11-02 10:03:09npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2022-11-02 10:03:09npm notice created a lockfile as package-lock.json. You should commit this file.
2022-11-02 10:03:09npm notice save @cubejs-backend/bigquery-driver is being moved from dependencies to devDependencies
2022-11-02 10:03:05> @cubejs-backend/cubestore@0.31.5 postinstall /cube/node_modules/@cubejs-backend/cubestore
2022-11-02 10:03:05> node bin/post-install
2022-11-02 10:03:05[sqlite3] Success: "/cube/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node" is installed via remote
2022-11-02 10:03:04> sqlite3@5.0.11 install /cube/node_modules/sqlite3
2022-11-02 10:03:04> node-pre-gyp install --fallback-to-build
2022-11-02 10:03:04[@cubejs-backend/native] Success: "/cube/node_modules/@cubejs-backend/native/native/index.node" is installed via remote
2022-11-02 10:02:58> @cubejs-backend/native@0.31.10 install /cube/node_modules/@cubejs-backend/native
2022-11-02 10:02:58> node-pre-gyp install || echo 'Your system is not supported by @cubejs-backend/native, some feature will be unavailable.'
2022-11-02 10:02:58gyp ERR! stack at ChildProcess.emit (events.js:400:28)
2022-11-02 10:02:58gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
2022-11-02 10:02:58gyp ERR! System Linux 4.14.294-220.533.amzn2.x86_64
2022-11-02 10:02:58gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-11-02 10:02:58gyp ERR! cwd /cube/node_modules/java
2022-11-02 10:02:58gyp ERR! node -v v14.20.0
2022-11-02 10:02:58gyp ERR! node-gyp -v v5.1.0
2022-11-02 10:02:58gyp ERR! not ok
2022-11-02 10:02:58gyp ERR! configure error
2022-11-02 10:02:58gyp ERR! stack Error: `gyp` failed with exit code: 1
2022-11-02 10:02:58gyp ERR! stack at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
2022-11-02 10:02:58(node:108) UnhandledPromiseRejectionWarning: TypeError [ERR_STREAM_NULL_VALUES]: May not write null values to stream
2022-11-02 10:02:58at new NodeError (internal/errors.js:322:7)
2022-11-02 10:02:58at Socket.Writable.write (internal/streams/writable.js:272:11)
2022-11-02 10:02:58at /cube/node_modules/java/findJavaHome.js:6:18
2022-11-02 10:02:58at /cube/node_modules/find-java-home/dist/index.js:103:21
2022-11-02 10:02:58at step (/cube/node_modules/find-java-home/dist/index.js:46:23)
2022-11-02 10:02:58at Object.next (/cube/node_modules/find-java-home/dist/index.js:27:53)
2022-11-02 10:02:58at fulfilled (/cube/node_modules/find-java-home/dist/index.js:18:58)
2022-11-02 10:02:58(Use `node --trace-warnings ...` to show where the warning was created)
2022-11-02 10:02:58(node:108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2022-11-02 10:02:58(node:108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2022-11-02 10:02:58gyp: Call to 'node findJavaHome.js' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
2022-11-02 10:02:57> java@0.12.2 install /cube/node_modules/java
2022-11-02 10:02:57> node-gyp rebuild
2022-11-02 10:02:57make: Leaving directory '/cube/node_modules/thrift/node_modules/ws/build'
2022-11-02 10:02:57CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
2022-11-02 10:02:57make: Entering directory '/cube/node_modules/thrift/node_modules/ws/build'
2022-11-02 10:02:56> ws@0.4.32 install /cube/node_modules/thrift/node_modules/ws
2022-11-02 10:02:56> (node-gyp rebuild 2> builderror.log) || (exit 0)
2022-11-02 10:02:56oracledb ** To use node-oracledb:
2022-11-02 10:02:56oracledb ** - Oracle Client libraries (64-bit) must be configured with ldconfig or LD_LIBRARY_PATH
2022-11-02 10:02:56oracledb ** - To get libraries, install an Instant Client Basic or Basic Light package from
2022-11-02 10:02:56oracledb ** https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html
2022-11-02 10:02:56oracledb **
2022-11-02 10:02:56oracledb ** Installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
2022-11-02 10:02:56oracledb ********************************************************************************
2022-11-02 10:02:56oracledb ********************************************************************************
2022-11-02 10:02:56oracledb ** Node-oracledb 4.2.0 installed for Node.js 14.20.0 (linux, x64)
2022-11-02 10:02:56oracledb **
2022-11-02 10:02:56> oracledb@4.2.0 install /cube/node_modules/oracledb
2022-11-02 10:02:56> node package/install.js
2022-11-02 10:02:41npm WARN rm not removing /cube/node_modules/.bin/mime as it wasn't installed by /cube/node_modules/mime
2022-11-02 10:02:40npm WARN rm not removing /cube/node_modules/.bin/uuid as it wasn't installed by /cube/node_modules/uuid
2022-11-02 10:02:40npm WARN rm not removing /cube/node_modules/.bin/semver as it wasn't installed by /cube/node_modules/semver
2022-11-02 10:02:40npm WARN rm not removing /cube/node_modules/.bin/node-pre-gyp as it wasn't installed by /cube/node_modules/@mapbox/node-pre-gyp
2022-11-02 10:02:09npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
2022-11-02 10:01:54npm WARN deprecated oracledb@4.2.0: Update to node-oracledb 5
2022-11-02 10:01:36npm WARN deprecated @hapi/pinpoint@2.0.0: Moved to 'npm install @sideway/pinpoint'
2022-11-02 10:01:36npm WARN deprecated @hapi/formula@2.0.0: Moved to 'npm install @sideway/formula'
2022-11-02 10:01:36npm WARN deprecated @hapi/address@4.1.0: Moved to 'npm install @sideway/address'
2022-11-02 10:01:34npm WARN deprecated @hapi/joi@17.1.1: Switch to 'npm install joi'
2022-11-02 10:01:26npm WARN deprecated har-validator@5.1.5: this library is no longer supported
2022-11-02 10:01:25npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
2022-11-02 10:01:25npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2022-11-02 10:01:21npm WARN deprecated @aws-sdk/eventstream-marshaller@3.49.0: The package @aws-sdk/eventstream-marshaller has been renamed to @aws-sdk/eventstream-codec. Please install the renamed package.
2022-11-02 10:01:15npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
2022-11-02 10:01:14npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
2022-11-02 10:01:14npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
2022-11-02 10:01:14npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
2022-11-02 10:01:12npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
2022-11-02 10:01:12npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
2022-11-02 10:00:58npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
2022-11-02 10:00:51npm WARN deprecated @aws-sdk/eventstream-marshaller@3.40.0: The package @aws-sdk/eventstream-marshaller has been renamed to @aws-sdk/eventstream-codec. Please install the renamed package.
2022-11-02 10:00:42npm WARN deprecated gcs-resumable-upload@3.6.0: gcs-resumable-upload is deprecated. Support will end on 11/01/2023
```

**Comment by paveltiunov** [comment]
@carlonuccio I guess you're trying to use Playground in a production environment which isn't possible with open source version of Cube. You can do it in Cube Cloud, however.

**Comment by mk-nuccioc** [comment]
I'm using `CUBEJS_DEV_MODE: true`. Doesn't work on ECS Fargate?

**Comment by paveltiunov** [comment]
@mk-nuccioc Yep. Dev mode is supposed only for local development and shouldn't be used when deployed to a production environment.
