### ISSUE TITLE
Error: Cannot find module '/cube/conf/cube.js'

### ISSUE THREAD

**Issue by apotplant** [cube-js/cube.js#5588]
I followed the [documentation](https://cube.dev/docs/getting-started/docker) to installing cubejs in docker and came across this issue. This is probably something I am missing. Could someone be able to point me in the right direction?

1. Installed Docker Desktop (Docker version 20.10.20, build 9fdeb9c)
2. Run command, `docker run -p 4000:4000 -p 3000:3000 -v ${PWD}:/cube/conf -e CUBEJS_DEV_MODE=true cubejs/cube`
3. Came across this error
```
Cube.js Error ---------------------------------------
Error: Cannot find module '/cube/conf/cube.js'
Require stack:
- /cube/node_modules/@cubejs-backend/server/dist/src/server/container.js
- /cube/node_modules/@cubejs-backend/server/dist/src/command/server.js
- /cube/node_modules/@cubejs-backend/server/dist/command/server.js
- /cube/node_modules/@cubejs-backend/shared/dist/src/package.js
- /cube/node_modules/@cubejs-backend/shared/dist/src/index.js
- /cube/node_modules/cubejs-cli/dist/src/command/proxy-command.js
- /cube/node_modules/cubejs-cli/dist/src/command/server.js
- /cube/node_modules/cubejs-cli/dist/src/cli.js
- /cube/node_modules/cubejs-cli/dist/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at /cube/node_modules/@cubejs-backend/server/src/server/container.ts:314:18
    at ServerContainer.loadConfigurationFromFile (/cube/node_modules/@cubejs-backend/server/src/server/container.ts:314:18)
```

**Comment by dybxin** [comment]
@apotplant  In a new folder for your project, run the command.  It should be executed under the relevant project directory.

**Comment by paveltiunov** [comment]
Please feel free to reopen if issue is still there.
