### ISSUE TITLE
cubestore-router  won't create in argocd with assuming role 

### ISSUE THREAD

**Issue by Hankier** [cube-js/cube.js#5675]
**Describe the bug**
Trying to create helm chart of cubestore on argocd using assumable IAM Role.

Here is an error trace:
```2022-11-25 09:22:27,402 INFO  [cubestored] <pid:1> Cube Store version 0.31.17
2022-11-25 09:22:27,402 DEBUG [cubestored] <pid:1> New process started
2022-11-25 09:22:27,403 TRACE [cubestore::telemetry] <pid:1> agent endpoint url: None
2022-11-25 09:22:27,407 INFO  [cubestore::http::status] <pid:1> Serving status probes at 0.0.0.0:3031
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { field: "missing field `AssumeRoleWithWebIdentityResult`" }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/aws-creds-0.24.1/src/credentials.rs:141:89
stack backtrace:
   0:     0x556197a2704d - std::backtrace_rs::backtrace::libunwind::trace::h66824bd979b46652
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x556197a2704d - std::backtrace_rs::backtrace::trace_unsynchronized::h0caf895dc6521160
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556197a2704d - std::sys_common::backtrace::_print_fmt::h8ee19c74892f96ef
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x556197a2704d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4f38873b172b3ee3
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x556197a4fadc - core::fmt::write::h95bc5c1a2dab38ae
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/core/src/fmt/mod.rs:1197:17
   5:     0x556197a20b11 - std::io::Write::write_fmt::hcbe645da27d05687
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/io/mod.rs:1672:15
   6:     0x556197a28955 - std::sys_common::backtrace::_print::h491b32351e64ba40
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x556197a28955 - std::sys_common::backtrace::print::h95813b9263ac2531
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x556197a28955 - std::panicking::default_hook::{{closure}}::h97b51a053e0a66a6
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:295:22
   9:     0x556197a28676 - std::panicking::default_hook::h4e7a054eecf2a40c
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:314:9
  10:     0x556197a28ee6 - std::panicking::rust_panic_with_hook::hc34128de9b2f1619
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:698:17
  11:     0x556197a28dd7 - std::panicking::begin_panic_handler::{{closure}}::h9b93455039a2a266
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:588:13
  12:     0x556197a27504 - std::sys_common::backtrace::__rust_end_short_backtrace::he9bdd19ae989173a
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x556197a28b09 - rust_begin_unwind
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:584:5
  14:     0x5561958a51c3 - core::panicking::panic_fmt::h30f2f0b84ee39ba8
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/core/src/panicking.rs:142:14
  15:     0x5561958a52b3 - core::result::unwrap_failed::hf9edc2a856335168
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/core/src/result.rs:1805:5
  16:     0x556196841713 - awscreds::credentials::Credentials::from_sts::hbde4da9b42273ac1
  17:     0x556196840cf2 - awscreds::credentials::Credentials::from_sts_env::hd3a973f8f7b6673a
  18:     0x55619684182f - awscreds::credentials::Credentials::new::h4f763f1ea1b760ed
  19:     0x556195d342fd - cubestore::remotefs::s3::S3RemoteFs::new::h9ef16158f0bf85ed
  20:     0x556195a085ca - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h86bbefab7712e286
  21:     0x556195a362ef - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf4383dc8dd57527a
  22:     0x556195a2884e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hccbcd389935f620b
  23:     0x556195a1b09f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb014f27541b1fb17
  24:     0x556195a0ad8c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h90a87321ee74b2b2
  25:     0x5561959fa4a2 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4dc6e3db31012bcc
  26:     0x556195a07ee9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h857415c65a5c5356
  27:     0x556195a30f2f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he15a606c7728e627
  28:     0x556195a47f5e - cubestore::config::Config::configure_injector::{{closure}}::{{closure}}::h1e98ac99b827d536
  29:     0x556195a32f35 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::heda983abdd1d1d98
  30:     0x556195a0fbbf - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha396a325a7d77ad3
  31:     0x556195a4d7a5 - cubestored::main::{{closure}}::haa9c2349c882e6e1
  32:     0x556195b59b9d - std::thread::local::LocalKey<T>::with::h42229dc88e01fb48
  33:     0x556195ad7b4a - tokio::park::thread::CachedParkThread::block_on::h30e6a551fece6b14
  34:     0x556195be7427 - tokio::runtime::thread_pool::ThreadPool::block_on::h86f117739fa92738
  35:     0x556195b93f4d - tokio::runtime::Runtime::block_on::h7c52200c38355111
  36:     0x556195add24e - cubestored::main::h72af4168bd6e9c95
  37:     0x556195ac7cc3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5f7f2488e2ac4d58
  38:     0x556195b24bd9 - std::rt::lang_start::{{closure}}::h9f0f309c7dad2522
  39:     0x556197a1a4de - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha8a8e65ef30bbc60
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/core/src/ops/function.rs:280:13
  40:     0x556197a1a4de - std::panicking::try::do_call::hf31b0c375d768911
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:492:40
  41:     0x556197a1a4de - std::panicking::try::he7eee203c4f60352
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:456:19
  42:     0x556197a1a4de - std::panic::catch_unwind::h454666a6b91fdf61
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panic.rs:137:14
  43:     0x556197a1a4de - std::rt::lang_start_internal::{{closure}}::h379590a88f2dcb30
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/rt.rs:128:48
  44:     0x556197a1a4de - std::panicking::try::do_call::h6290c1b8cfa21d25
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:492:40
  45:     0x556197a1a4de - std::panicking::try::ha9e207d6028be8bb
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:456:19
  46:     0x556197a1a4de - std::panic::catch_unwind::hb3824d741f348baf
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panic.rs:137:14
  47:     0x556197a1a4de - std::rt::lang_start_internal::hbcf57b2e346b06f1
                               at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/rt.rs:128:20
  48:     0x556195add572 - main
  49:     0x7fbf7d71409b - __libc_start_main
  50:     0x5561958ed00a - _start
  51:                0x0 - <unknown>
 
```

How can I get more info what is causing this issue?

**To Reproduce**
Use argocd for deploying.

**Expected behavior**
cubestore-router is created using assuming role. 

**Screenshots**

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

**Version:**
latest

**Additional context**

**Comment by paveltiunov** [comment]
@Hankier Is it the same as #5330 ?

**Comment by Hankier** [comment]
Found a reason, can be closed.

**Comment by Hankier** [comment]
@quasi-coherent In my case I was using IAM Role instead of user with aws access/secret.

Had no problem with keys, make  sure you have proper values in those enviroments in your cubestore router and workers. 
Hard to tell whats wrong without your helm-charts.

**Comment by quasi-coherent** [comment]
@Hankier I was trying to avoid using keys and instead use IRSA roles, but my problem was the service account annotations were incorrect.  Glad we both got it figured out!
