### ISSUE TITLE
Unexpected errors during concurrent  refresh of pre-aggregations

### ISSUE THREAD

**Issue by kaja78** [cube-js/cube.js#5715]
**Describe the bug**
We are seeing random errors in PreAggregation.ts tablesToVersionEntries() method during parallel pre-agg refresh:

```
TypeError: Cannot read properties of undefined (reading 'map')
    at tablesToVersionEntries (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:138:10)
    at PreAggregationLoadCache.calculateVersionEntries (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:282:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at mostRecentResult (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:576:9)
    at PreAggregationLoader.loadPreAggregation (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:510:22)
    at QueryOrchestrator.fetchQuery (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:104:59)
    at OrchestratorApi.executeQuery (/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:64:20)
    at /cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:479:13
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at RefreshScheduler.runScheduledRefresh (/cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:165:9)
    at async Promise.all (index 0)
    at Timeout._onTimeout (/cube/node_modules/@cubejs-backend/shared/src/promises.ts:139:9)
```
It looks like, that implementation of async getTablesQuery() is not safe for concurrency. Looks like there is issue with returning `tables` field, which might be modified by concurrent async reset() call: 

```
  protected async getTablesQuery(preAggregation) {
    const redisKey = this.tablesRedisKey(preAggregation);
    if (!this.tables[redisKey]) {
      this.tables[redisKey] = this.preAggregations.options.skipExternalCacheAndQueue && preAggregation.external ?
        await this.fetchTablesNoCache(preAggregation) :
        await this.tablesFromCache(preAggregation);
    }
    return this.tables[redisKey];
  }
```
Disclaimer: I am not TypeScript expert at all. However I was able to replicate the issue using exploratory testing on PreAgg mock implementation (see bellow).

**To Reproduce**
The bug is reproducible using bellow jest test.
```
const KEY = "key";
const CACHE = "cache"
const NO_CACHE = "nocache"

class PreAggMock {
  private tables: any ={}
  public undefinedValueCount = 0;

  private randomWait() {
    const ms = Math.round(Math.random()*10);
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  public async checkValue() {
    const value = await this.getTablesQuery();
    if (!value) {
      this.undefinedValueCount++;
    }
  }

  public async checkValueFixed() {
    const value = await this.getTablesQueryFixed();
    if (!value) {
      this.undefinedValueCount++;
    }
  }

  protected async getTablesQuery() {
    if (!this.tables[KEY]) {
      this.tables[KEY] = Math.random()>0.5 ? await this.fetchTablesNoCache() : await this.tablesFromCache();
    }
    return this.tables[KEY];
  }

  protected async getTablesQueryFixed() {
    const value = this.tables[KEY];
    if (value) {
      return value;
    }

    const newValue = await (Math.random()>0.5 ? this.fetchTablesNoCache() : this.tablesFromCache());
    this.tables[KEY] = newValue;
    return newValue;
  }

  public async reset() {
    await this.tablesFromCache();
    this.tables = {};
  }

  public async tablesFromCache() {
    await this.randomWait();
    return CACHE;
  }

  protected async fetchTablesNoCache() {
    await this.randomWait();
    return NO_CACHE;
  }
}

describe("PreAgg concurrency test", () => {

  it("getTablesQuery() should never return undefined", async () => {
    const preAgg = new PreAggMock();
    const iterations = 100;
    var p:Promise<any>[] = new Array(iterations);
    for (let i=0;i<p.length/2;i++) {
      p[i*2]=preAgg.reset();
      p[i*2+1]=preAgg.checkValue();
    }
    await Promise.all(p);
    expect(preAgg.undefinedValueCount).toBe(0)
  });

  it("getTablesQueryFixed() should never return undefined", async () => {
    const preAgg = new PreAggMock();
    const iterations = 100;
    var p:Promise<any>[] = new Array(iterations);
    for (let i=0;i<p.length/2;i++) {
      p[i*2]=preAgg.reset();
      p[i*2+1]=preAgg.checkValueFixed();
    }
    await Promise.all(p);
    expect(preAgg.undefinedValueCount).toBe(0)
  });
});
```

**Expected behavior**
No errors during concurrent refresh of pre-aggs. Async getTablesQuery() method is  implemented in concurrency safe way. Proposal: Store the return value in local constant. Where applicable, replace access to `tables` field by local constant.

**Screenshots**
N/A

**Minimally reproducible Cube Schema**
N/A

**Version:**
v0.30.14

**Additional context**
N/A

**Comment by paveltiunov** [comment]
@kaja78 This was fixed a while ago. Could you please check with latest version?
