### ISSUE TITLE
Cube 'Test' not found for path 'Test.transactionCount'

### ISSUE THREAD

**Issue by quasi-coherent** [cube-js/cube.js#5879]
**Problem**

I have deployed cubejs (the API, cubestore, and redis) in a Kubernetes cluster with a Helm chart I've created.  I am submitting the following request to the pod running the API service:

```
> $ curl -H "content-type:application/json" -H "Authorization: <my JWT>" --data '{"query": {"measures":["Test.transactionCount"]}}' localhost:4000/cubejs-api/v1/load
```

but I get this error back:

```
{"type":"UserError","error":"Cube 'Test' not found for path 'Test.transactionCount'","stack":"Error: Cube 'Test' not found for path 'Test.transactionCount'\n    at CubeEvaluator.byPath (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeEvaluator.js:359:13)\n    at CubeEvaluator.parsePath (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeEvaluator.js:375:10)\n    at BaseMeasure.path (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseMeasure.js:163:37)\n    at /cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1478:15\n    at _map (/cube/node_modules/ramda/src/internal/_map.js:7:19)\n    at map (/cube/node_modules/ramda/src/map.js:83:14)\n    at /cube/node_modules/ramda/src/internal/_dispatchable.js:50:15\n    at /cube/node_modules/ramda/src/internal/_curry2.js:26:18\n    at f1 (/cube/node_modules/ramda/src/internal/_curry1.js:19:17)\n    at /cube/node_modules/ramda/src/internal/_pipe.js:3:14\n    at /cube/node_modules/ramda/src/internal/_pipe.js:3:27\n    at /cube/node_modules/ramda/src/internal/_pipe.js:3:27\n    at /cube/node_modules/ramda/src/internal/_pipe.js:3:27\n    at /cube/node_modules/ramda/src/internal/_arity.js:11:19\n    at SnowflakeQuery.collectFrom (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1486:6)\n    at SnowflakeQuery.collectFromMembers (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1468:17)\n    at SnowflakeQuery.collectJoinHints (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1447:17)\n    at SnowflakeQuery.get allJoinHints [as allJoinHints] (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:302:38)\n    at SnowflakeQuery.initFromOptions (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:244:47)\n    at new BaseQuery (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:96:10)\n    at new SnowflakeQuery (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/SnowflakeQuery.js:14:1)\n    at Object.createQuery (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/QueryBuilder.js:58:10)"}
```

* What does this error mean?  
* If it means that the service can't find the schema files in the image, then where are these files supposed to be?  
* What does the environment variable `CUBEJS_SCHEMA_PATH` even do?  
 
The [documentation](https://cube.dev/docs/reference/environment-variables#cubejs-schema-path) states plainly that it's, "The path where Cube loads schemas from."  It also states that the default is `schema`, which is not correct -- if the variable is unset there is no default.   I've tried setting this variable to `schema`, which is the location of my schema files appended to the `WORKDIR` of the image

```
root@cubejs-api-f6987fbbf-65zch:/cube/conf# echo $CUBEJS_SCHEMA_PATH
schema
root@cubejs-api-f6987fbbf-65zch:/cube/conf# ls schema
EventAuthentication.ts	Test.ts
root@cubejs-api-f6987fbbf-65zch:/cube/conf# cat schema/Test.ts
cube(`Test`, {
  sql: `SELECT * FROM BETA.TEST`,

  measures: {
    transactionCount: {
      type: `count`,
    },
    revenue: {
      type: `sum`,
      sql: `payment`,
    },
  },

  dimensions: {
    user: {
      sql: `${CUBE}."USER"`,
      type: `string`,
    },

    payment: {
      sql: `${CUBE}."PAYMENT"`,
      type: `number`,
    },
  }
})
```

with the same result.  I've tried not setting this variable with the same result.  Where else could they possibly go?  Does this error mean something else?

This is the Dockerfile that I'm using:

```
FROM cubejs/cube@sha256:596c13f981b577784cfd98b99ca172dbf9c6b8a3998d8e5fcb55373e481bc8aa

COPY services/cubejs/schema /cube/conf/schema
RUN apt update && apt install -y libssl-dev ca-certificates
RUN npm install && npm install async --save
```

I've tried changing the third line to `COPY services/cubejs/schema .` and it complains that 

```
{"error":"Error: ENOENT: no such file or directory, scandir '/cube/conf/schema'","stack":"Error: ENOENT: no such file or directory, scandir '/cube/conf/schema'"}
```

which is precisely where the schema files were in previous attempts!  

**Related Cube.js schema**

The one in the above shell snippet.

**Comment by quasi-coherent** [comment]
As it turns out, files with a `.ts` extension are not found.  They must be a `.js` file.
