### ISSUE TITLE
CubeJS restart all the time

### ISSUE THREAD

**Issue by lucienfregosibodyguard** [cube-js/cube.js#5896]
**Describe the bug**
WIth a cubejs deployed on kubernetes (v0.31.31) the pod are restarting a lot (every ten minutes with this message 
```
Refresh Scheduler Interval Error: undefined                                      
{}                                                                               
Previous interval #1 was not finished with 30000 interval                        
Stream closed EOF for cubejs/cube-prd-master-57cbddb985-jpvkz (cube)             
Warning. There is no cube.js file. Continue with environment variables           
🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=prod
🦅 Dev environment available at http://localhost:4000/                            
🔗 Cube SQL (pg) is listening on 0.0.0.0:5432                                    
🚀 Cube API server (0.31.31) is listening on 4000                                
TypeError: Cannot read property 'callback' of undefined                          
    at normal_reply (/cube/node_modules/redis/index.js:651:28)                   
    at RedisClient.return_reply (/cube/node_modules/redis/index.js:753:9)        
    at JavascriptRedisParser.returnReply (/cube/node_modules/redis/index.js:138:1
    at JavascriptRedisParser.execute (/cube/node_modules/redis-parser/lib/parser.
    at Socket.<anonymous> (/cube/node_modules/redis/index.js:219:27)             
    at Socket.emit (events.js:400:28)                                            
    at addChunk (internal/streams/readable.js:293:12)                            
    at readableAddChunk (internal/streams/readable.js:267:9)                     
    at Socket.Readable.push (internal/streams/readable.js:206:10)                
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**To Reproduce**
1. Deploy Cubejs over a kubernetes cluster

**Expected behavior**
I expect cubejs to be stable 

**Minimally reproducible Cube Schema**
Seems not related to the schema

**Version:**
0.31.31

**Comment by paveltiunov** [comment]
@lucienfregosibodyguard It's one of the reasons we're replacing Redis with Cube Store. Please see https://cube.dev/blog/replacing-redis-with-cube-store for more details.

**Comment by mauriciocirelli** [comment]
> @lucienfregosibodyguard It's one of the reasons we're replacing Redis with Cube Store. Please see https://cube.dev/blog/replacing-redis-with-cube-store for more details.

Is there any doc showing how to deploy CubeJS in Kubernetes without using Redis?

**Comment by paveltiunov** [comment]
@mauriciocirelli There's no example, but you can use `memory` setting for https://cube.dev/docs/reference/environment-variables/#cubejs-cache-and-queue-driver if you have only one Cube instance in your deployment. It isn't suitable for production purposes, though.
