### ISSUE TITLE
TypeError: externalDriverFactory is not a function on testConnections()

### ISSUE THREAD

**Issue by 0x62** [cube-js/cube.js#605]
**Describe the bug**
I've implemented a health check endpoint with the below code:

```
server.listen().then(({ app, port }) => {
  console.log(`🚀 Cube.js server is listening on ${port}`);

  app.get('/healthz', async (req, res) => {
    try {
      await server.testConnections()
      res.status(200).send('Healthy')
    } catch (err) {
      console.log(err)
      res.status(500).send('Error')
    }
  });
}).catch(e => {
  console.error('Fatal error during server start: ');
  console.error(e.stack || e);
});
```

This code works fine usually, but seemingly at random it will stop working and start throwing an error. Restarting the process fixes it temporarily:

```
2020-04-21T15:17:26.049948+00:00 app[web.1]: TypeError: this.externalDriverFactory is not a function
2020-04-21T15:17:26.049950+00:00 app[web.1]:     at getExternalDriverFactory (/app/node_modules/@cubejs-backend/server-core/core/index.js:427:39)
2020-04-21T15:17:26.049951+00:00 app[web.1]:     at OrchestratorApi.testDriverConnection (/app/node_modules/@cubejs-backend/server-core/core/OrchestratorApi.js:84:28)
2020-04-21T15:17:26.049951+00:00 app[web.1]:     at OrchestratorApi.testConnection (/app/node_modules/@cubejs-backend/server-core/core/OrchestratorApi.js:78:12)
2020-04-21T15:17:26.049952+00:00 app[web.1]:     at /app/node_modules/@cubejs-backend/server-core/core/index.js:495:34
2020-04-21T15:17:26.049953+00:00 app[web.1]:     at Array.forEach (<anonymous>)
2020-04-21T15:17:26.049954+00:00 app[web.1]:     at CubejsServerCore.testConnections (/app/node_modules/@cubejs-backend/server-core/core/index.js:493:53)
2020-04-21T15:17:26.049955+00:00 app[web.1]:     at CubejsServer.testConnections (/app/node_modules/@cubejs-backend/server/index.js:87:22)
2020-04-21T15:17:26.049956+00:00 app[web.1]:     at /app/index.js:29:20
2020-04-21T15:17:26.049956+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-04-21T15:17:26.049957+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2020-04-21T15:17:25.959831+00:00 heroku[router]: at=info method=HEAD path="/healthz" host=analytics.infstream.com request_id=ddfd3b3e-1b02-493a-bd3b-bc53eb40d9cb fwd="45.32.107.181,162.158.107.15" dyno=web.1 connect=1ms service=4ms status=500 bytes=249 protocol=https
2020-04-21T15:17:26.054109+00:00 heroku[router]: at=info method=HEAD path="/healthz" host=analytics.infstream.com request_id=ea22cb29-54d0-4970-bfa1-5f9e9bd596b2 fwd="2001:19f0:4400:402e::1,162.158.165.73" dyno=web.1 connect=3ms service=5ms status=500 bytes=249 protocol=https
2020-04-21T15:17:28.622743+00:00 heroku[web.1]: State changed from up to starting
2020-04-21T15:17:28.607944+00:00 heroku[web.1]: Restarting
2020-04-21T15:17:39.032771+00:00 heroku[web.1]: State changed from starting to up
2020-04-21T15:17:38.620140+00:00 app[web.1]: 🚀 Cube.js server is listening on 31226
2020-04-21T15:17:50.402896+00:00 heroku[router]: at=info method=GET path="/healthz" host=analytics.infstream.com request_id=e5c1b9ee-ab66-477e-bf4c-f36479bcbbcf fwd="62.68.160.154,141.101.105.43" dyno=web.1 connect=1ms service=27ms status=200 bytes=237 protocol=https
```

This is how I'm initializing CubeJs:

```
const db = new URL(process.env.DATABASE_URL)
const server = new CubejsServer({
  dbType: 'postgres',
  driverFactory: () => new PostgresDriver({
    host: db.hostname,
    database: db.pathname.replace('/', ''),
    port: db.port,
    user: db.username,
    password: db.password,
  }),
  orchestratorOptions: {
    queryCacheOptions: {
      queueOptions: {
        executionTimeout: 6000,
        concurrency: 10,
      },
    },
  },
});
```

**To Reproduce**
1. Call `testConnections` method
2. Wait for error to be thrown

**Expected behavior**
`testConnections` should only throw an error when connection to database or redis fails.

**Version:**
```
@cubejs-backend/postgres-driver: ^0.18.12
@cubejs-backend/server: ^0.18.12
```

**Comment by paveltiunov** [comment]
@0x62 Hey Ben! Could you please update? Should be fixed already.

**Comment by 0x62** [comment]
Thanks, I've updated and will reopen if it persists
