### ISSUE TITLE
Cannot perform CREATE TEMPSTAGE. This session does not have a current schema. Call 'USE SCHEMA'

### ISSUE THREAD

**Issue by nholmes3** [cube-js/cube.js#6109]
**Describe the bug**

When querying for large amounts of data against our Snowfalke database:

OperationFailedError: Cannot perform CREATE TEMPSTAGE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
    at createError (/cube/node_modules/snowflake-sdk/lib/errors.js:536:15)
    at Object.exports.createOperationFailedError (/cube/node_modules/snowflake-sdk/lib/errors.js:315:10)
    at Object.callback (/cube/node_modules/snowflake-sdk/lib/services/sf.js:647:28)
    at /cube/node_modules/snowflake-sdk/lib/http/base.js:111:25
    at done (/cube/node_modules/urllib/lib/urllib.js:589:5)
    at /cube/node_modules/urllib/lib/urllib.js:953:9
    at decodeContent (/cube/node_modules/urllib/lib/urllib.js:740:14)
    at handleResponseCloseAndEnd (/cube/node_modules/urllib/lib/urllib.js:924:7)
    at IncomingMessage.<anonymous> (/cube/node_modules/urllib/lib/urllib.js:962:7)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    
There is no way to pass the schema into the cubejs configuration and setting the default_namespace for the user in snowflake does not help.

**To Reproduce**
Try to query large amount of snowflake data through cube without hitting a pre-aggregation

**Expected behavior**
The query should succeed assuming Snowflake connection configuration is defined correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/69873985/216428751-d77258bc-ab86-4c55-b959-141505f5a486.png)

**Version:**
v0.31.36

**Comment by igorlukanin** [comment]
Does this still reproduce on the latest version of Cube?
