### ISSUE TITLE
Error while creating Pre-Aggregate table: Custom type 'tinyint' is not supported

### ISSUE THREAD

**Issue by rmrod** [cube-js/cube.js#6172]
**Describe the bug**
When configuring a Pre-Aggregate for a cube whose datasource is mongobi and which has a column whose type is boolean, the error below occurs:

```
Error: Error during create table: CREATE TABLE dev_pre_aggregations.entity_main_0zx0a4wb_qpmhotxv_1hut8n8 (`entity__deleted` tinyint, `entity__id` bigint) INDEX entity_main_index_name_0zx0a4wb_qpmhotxv_1hut8n8 (`entity__id`) LOCATION ?: Custom type 'tinyint' is not supported
     at QueryQueue.parseResult (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:416:13)
     at QueryQueue.executeQueryInQueue (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:397:19)
     at processTicksAndRejections (internal/process/task_queues.js:95:5)
     at PreAggregationLoader.loadPreAggregationWithKeys (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:770:7)
     at PreAggregationLoader.loadPreAggregation (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:553:22)
     at preAggregationPromise (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:2122:30)
     at QueryOrchestrator.fetchQuery (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:196:9)
     at OrchestratorApi.executeQuery (/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:97:20)
     at /cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:598:13
     at async Promise.all (index 0)
     at RefreshScheduler.refreshPreAggregations (/cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:583:5)
     at async Promise.all (index 1)
     at RefreshScheduler.runScheduledRefresh (/cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:283:9)

```

**To Reproduce**
1. Setup a MongoDB with MongoBI Connector
2. Start mongosqld with DRDL schema that has a column that has MongoType=bool and SqlType=boolean
4. Configure a Cube and a Pre-Aggregate with a boolean column
5. Start Cubejs with mongobi datasource
6. See the error when trying to create de Pre-Aggregate table

**Expected behavior**
That the Pre-Aggregate is created and the queries are accelerated by it.

**Screenshots**
N/A

**Minimally reproducible Cube Schema**

mongobi-schema.drdl
```yaml
schema:
  - db: test-database
    tables:
      - table: entity
        collection: entity
        pipeline: [ ]
        columns:
          - Name: _id
            MongoType: int
            SqlName: _id
            SqlType: int
          - Name: deleted
            MongoType: bool
            SqlName: deleted
            SqlType: boolean
```

```javascript
cube(`Entity`, {
    dataSource: `default`,

    sql: `SELECT *
          FROM \`test-database\`.\`entity\``,

    preAggregations: {
        main: {
            measures: [],
            dimensions: [
                Entity.id,
                Entity.deleted
            ]
        }
    },

    measures: {},

    dimensions: {
        id: {
            sql: `_id`,
            type: `number`,
            primaryKey: true,
            shown: true,
            title: `ID`
        },
        deleted: {
            sql: `${CUBE}.\`deleted\``,
            type: `boolean`,
            title: `Deleted`
        }
    }
});

```

**Version:**
[e.g. 0.31.62]

**Additional context**
N/A

**Comment by ovr** [comment]
Released & fixed in [v0.31.64](https://github.com/cube-js/cube.js/releases/tag/v0.31.64)

Thanks!
