### ISSUE TITLE
Dashboard - Failed to compile.

### ISSUE THREAD

**Issue by luballe** [cube-js/cube.js#666]
**Describe the bug**
Failed to compile when starting the dashboard development server

**To Reproduce**

- OS version:
`Debian 10 (buster)`

- node version:
`v12.16.3`

- npm version:
`6.14.4`

- Install cube.js (0.19.21)
`npm install -g cubejs-cli`

- Create real time dashboard
`cubejs create real-time-dashboard -d mongobi`

- Update the .env file
```
CUBEJS_DB_HOST=localhost
CUBEJS_DB_NAME=stats
CUBEJS_DB_PORT=3307
CUBEJS_DB_TYPE=mongobi
CUBEJS_API_SECRET=SECRET
```

- Start the Cube.js development server
`$ npm run dev`

-  navigate to "Dashboard App,” select "React Antd Static" with "Chart.js," and click on the “Create dashboard app” button. Then hit the “Start” button

- The console appears with the following error:
```
Failed to compile.

./node_modules/@cubejs-client/ws-transport/dist/cubejs-client-ws-transport.js
Module not found: Can't resolve 'core-js/modules/es6.array.filter' in '/home/lballesterosp/real-time-dashboard/dashboard-app/node_modules/@cubejs-client/ws-transport/dist'
```

**Expected behavior**
Dashboard running OK

**Screenshots**
![image](https://user-images.githubusercontent.com/1441416/82853263-eae9e180-9eca-11ea-83ff-ddda4ac1247e.png)

![image](https://user-images.githubusercontent.com/1441416/82853294-005f0b80-9ecb-11ea-9d56-189625205039.png)

**Version:**
(0.19.21)

**Additional context**
- Full console output:

```
lballesterosp@instance-2:~/real-time-dashboard$ npm run dev                                                                                                                 [142/556]

> real-time-dashboard@0.0.1 dev /home/lballesterosp/real-time-dashboard
> node index.js

🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
🦅 Dev environment available at http://localhost:4000
🚀 Cube.js server (0.19.21) is listening on 4000
npx: installed 98 in 4.809s

Creating a new React app in /home/lballesterosp/real-time-dashboard/dashboard-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...


> core-js@2.6.11 postinstall /home/lballesterosp/real-time-dashboard/dashboard-app/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall /home/lballesterosp/real-time-dashboard/dashboard-app/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.6.5 postinstall /home/lballesterosp/real-time-dashboard/dashboard-app/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

+ cra-template@1.0.3
+ react-dom@16.13.1
+ react-scripts@3.4.1
+ react@16.13.1
added 1616 packages from 751 contributors and audited 1620 packages in 42.004s

59 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

Initialized a git repository.

Installing template dependencies using npm...
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-d[100/556]
3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @testing-library/react@9.5.0
+ @testing-library/user-event@7.2.1
+ @testing-library/jest-dom@4.2.4
added 36 packages from 56 contributors and audited 1656 packages in 13.225s

59 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Removing template package using npm...

npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >=
3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

removed 1 package and audited 1655 packages in 10.684s

59 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Git commit not created Error: Command failed: git commit -m "Initialize project using Create React App"
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)                                                                                                                                    [57/556]
    at tryGitCommit (/home/lballesterosp/real-time-dashboard/dashboard-app/node_modules/react-scripts/scripts/init.js:62:5)
    at module.exports (/home/lballesterosp/real-time-dashboard/dashboard-app/node_modules/react-scripts/scripts/init.js:334:25)
    at [eval]:3:14
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at evalScript (internal/process/execution.js:94:25) {
  status: 128,
  signal: null,
  output: [ null, null, null ],
  pid: 9006,
  stdout: null,
  stderr: null
}
Removing .git directory...

Success! Created dashboard-app at /home/lballesterosp/real-time-dashboard/dashboard-app
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd dashboard-app
  npm start

Happy hacking!
{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >=
3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN rc-picker@1.4.16 requires a peer of dayjs@^1.8.18 but none is installed. You must install peer dependencies yourself.                                               [14/556]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ react-router@5.2.0
+ chart.js@2.9.3
+ prop-types@15.7.2
+ react-chartjs-2@2.9.0
+ react-router-dom@5.2.0
+ antd@4.2.5
+ @cubejs-client/ws-transport@0.19.19
+ @cubejs-client/react@0.19.19
+ @cubejs-client/core@0.19.19
added 83 packages from 69 contributors, updated 1 package and audited 1739 packages in 22.768s

60 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

> dashboard-app@0.1.0 start /home/lballesterosp/real-time-dashboard/dashboard-app
> react-scripts start


ℹ ｢wds｣: Project is running at http://10.150.0.3/

ℹ ｢wds｣: webpack output is served from

ℹ ｢wds｣: Content not from webpack is served from /home/lballesterosp/real-time-dashboard/dashboard-app/public

ℹ ｢wds｣: 404s will fallback to /

Starting the development server...


Failed to compile.

./node_modules/@cubejs-client/ws-transport/dist/cubejs-client-ws-transport.js
Module not found: Can't resolve 'core-js/modules/es6.array.filter' in '/home/lballesterosp/real-time-dashboard/dashboard-app/node_modules/@cubejs-client/ws-transport/dist'

Compiling...

Failed to compile.

./node_modules/@cubejs-client/ws-transport/dist/cubejs-client-ws-transport.js
Module not found: Can't resolve 'core-js/modules/es6.array.filter' in '/home/lballesterosp/real-time-dashboard/dashboard-app/node_modules/@cubejs-client/ws-transport/dist'
```

**Comment by paveltiunov** [comment]
@luballe Hey Luis! Thanks for posting this! It should be fixed right now. Could you please check?

**Comment by luballe** [comment]
Thanks a lot Pavel. It works like a charm!!
=)
