### ISSUE TITLE
Error while installing CubeJS / MongoDB

### ISSUE THREAD

**Issue by mwaqarkhan1978** [cube-js/cube.js#757]
my environment details,
Windows 10. NPM installed. 

1- Step 1 (EXECUTING COMMAND cubejs create cubemong3 -d mongobi)

getting following error, 

- Installing DB driver dependencies
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path D:\data\repo\cubemong3\node_modules\pseudomap
npm ERR! dest D:\data\repo\cubemong3\node_modules\.pseudomap.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\data\repo\cubemong3\node_modules\pseudomap' -> 'D:\data\repo\cubemong3\node_modules\.pseudomap.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<<USERNAME>>\AppData\Roaming\npm-cache\_logs\2020-06-25T07_19_09_650Z-debug.log

Cube.js Error ---------------------------------------

Error: npm install --save @cubejs-backend/mongobi-driver failed with exit code 4294963238
    at ChildProcess.<anonymous> (C:\Users\<<USERNAME>>\AppData\Roaming\npm\node_modules\cubejs-cli\cubejsCli.js:31:16)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\<<USERNAME>>\AppData\Roaming\npm\node_modules\cubejs-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by vasilev-alex** [comment]
Hi @mwaqarkhan1978! Most likely this is an NPM related issue. 

Could you please refer to this page and see if that helps? https://docs.npmjs.com/common-errors
